### ISSUE TITLE
error "could not find caffe2_nvrtc.dll "

### ISSUE THREAD

**Issue by mickaelpruvost** [alievk/avatarify-python#103]
hello, when I'm running the file run_windows.bat , I got this message: **FileNotFoundError: Could not find module 'C:\SPB_Data\.conda\envs\avatarify\lib\site-packages\torch\lib\caffe2_nvrtc.dll' (or one of its dependencies). Try using the full path with constructor syntax.`**
I have checked and yet the dll is well in the folder ...

thank you for your help

MP
```
(avatarify) C:\WINDOWS\System32\avatarify>run_windows.bat

(avatarify) C:\WINDOWS\System32\avatarify>REM Web-camera device id

(avatarify) C:\WINDOWS\System32\avatarify>set CAMID=0

(avatarify) C:\WINDOWS\System32\avatarify>REM ################################################

(avatarify) C:\WINDOWS\System32\avatarify>REM Normally you don't want to change settings below

(avatarify) C:\WINDOWS\System32\avatarify>REM Conda environment name

(avatarify) C:\WINDOWS\System32\avatarify>set CONDA_ENV_NAME=avatarify
Traceback (most recent call last):
  File "cam_fomm.py", line 13, in <module>
    import torch
  File "C:\SPB_Data\.conda\envs\avatarify\lib\site-packages\torch\__init__.py", line 81, in <module>
    ctypes.CDLL(dll)
  File "C:\SPB_Data\.conda\envs\avatarify\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
**FileNotFoundError: Could not find module 'C:\SPB_Data\.conda\envs\avatarify\lib\site-packages\torch\lib\caffe2_nvrtc.dll' (or one of its dependencies). Try using the full path with constructor syntax.`**

**Comment by E3V3A** [comment]
Don't use funny chacacters in your directory paths.
```
C:\SPB_Data.conda\envs\avatarify\lib\site-packages\torch\lib\caffe2_nvrtc.dll
C:\SPB_Data\.conda\envs\avatarify\lib\site-packages\torch\lib\caffe2_nvrtc.dll
```

Even github have difficulties seeing the diff...

**Comment by mickaelpruvost** [comment]
thank you for your answer, I made a mistake when I copied pasted. As you can see in the message 

**FileNotFoundError: Could not find module 'C:\SPB_Data\.conda\envs\avatarify\lib\site-packages\torch\lib\caffe2_nvrtc.dll' (or one of its dependencies). Try using the full path with constructor syntax.`**

the directory path is well written but still the error message 

thanks

MP

**Comment by sanhedrin514** [comment]
I have the same error with no special characters

`(avatarify) C:\Users\sanhe\avatarify>set CONDA_ENV_NAME=avatarify
Traceback (most recent call last):
  File "cam_fomm.py", line 13, in <module>
    import torch
  File "C:\Users\sanhe\miniconda3\envs\avatarify\lib\site-packages\torch\__init__.py", line 81, in <module>
    ctypes.CDLL(dll)
  File "C:\Users\sanhe\miniconda3\envs\avatarify\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'C:\Users\sanhe\miniconda3\envs\avatarify\lib\site-packages\torch\lib\caffe2_nvrtc.dll' (or one of its dependencies). Try using the full path with constructor syntax.`

The file path was C:\Users\sanhe\miniconda3\envs\avatarify\**Lib**\site-packages\torch\lib\caffe2_nvrtc.dll  
but I changed it to matched the the lower caps to no effect

**Comment by E3V3A** [comment]
Not enough info! Please post more details with *OS, info, versions* with *screenshots* and *commands* + (text) *output* leading up to the issue. Otherwise close this.

**Comment by sanhedrin514** [comment]
Windows 10 64 bit
Visual Studio 16.5.3
Annaconda 4.8.2
Cuda 10.2.89
Git 2.26.2

`(base) C:\Users\sanhe>cd avatarify

(base) C:\Users\sanhe\avatarify>run_windows.bat

(base) C:\Users\sanhe\avatarify>REM Web-camera device id

(base) C:\Users\sanhe\avatarify>set CAMID=0

(base) C:\Users\sanhe\avatarify>REM ################################################

(base) C:\Users\sanhe\avatarify>REM Normally you don't want to change settings below

(base) C:\Users\sanhe\avatarify>REM Conda environment name

(base) C:\Users\sanhe\avatarify>set CONDA_ENV_NAME=avatarify
Traceback (most recent call last):
  File "cam_fomm.py", line 13, in <module>
    import torch
  File "C:\Users\sanhe\miniconda3\envs\avatarify\lib\site-packages\torch\__init__.py", line 81, in <module>
    ctypes.CDLL(dll)
  File "C:\Users\sanhe\miniconda3\envs\avatarify\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'C:\Users\sanhe\miniconda3\envs\avatarify\lib\site-packages\torch\lib\caffe2_nvrtc.dll' (or one of its dependencies). Try using the full path with constructor syntax.`

**Comment by maxjada** [comment]
I've solved deleting miniconda folder (i'd installed miniconda 3.7). Then I've download miniconda last versión 4.8.
Now it Works in Windows 10

**Comment by cciprianmihai** [comment]
The best and easiest solution I found is to downgrade Python version of the conda env to `3.7.5`:
```
conda activate my_env
conda install python=3.7.5
```

**Comment by alievk** [comment]
@cciprianmihai any thoughts why this could be the case?

@mickaelpruvost @sanhedrin514 could you try @cciprianmihai 's solution?

**Comment by cciprianmihai** [comment]
@alievk What I understand is that downgrading the Python version to `3.7.5`, Pytorch, and other modules, also, get downgraded to a functional version at the moment. 

I think this is a workaround until new updates with come.

**Comment by alievk** [comment]
I was thinking about fixing this version in the installation script. Let's see if this works for other users too.

**Comment by coolkat64** [comment]
Having the same problem and downgrading to 3.7.5 didn't do it for me

**Comment by JohanAR** [comment]
Anyone still having this issue with latest master?

**Comment by Kishan-Pandey** [comment]
Microsoft Windows [Version 10.0.18363.1556]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\Users\pande\Documents\Dewinter_BloodCell\dist\dwbd>dwbd.exe
Traceback (most recent call last):
  File "dwbd.py", line 32, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "torchf\torch\__init__.py", line 21, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "torchf\torch\_utils.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "torch\__init__.py", line 137, in <module>
    raise err
OSError: [WinError 126] The specified module could not be found. Error loading "C:\Users\pande\Documents\Dewinter_BloodCell\dist\dwbd\torch\lib\caffe2_nvrtc.dll" or one of its dependencies.
[852] Failed to execute script 'dwbd' due to unhandled exception!

C:\Users\pande\Documents\Dewinter_BloodCell\dist\dwbd>


Getting this error. Can anyone help with solutions other than those mentioned above?
