### ISSUE TITLE
DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by kratadata** [alievk/avatarify-python#111]
Error when running run_windows.bat

  File "cam_fomm.py", line 11, in <module>
    import cv2
ImportError: DLL load failed: The specified module could not be found.

Tried to install different opencv libraries to no avail. Any ideas how to solve this?

**Comment by E3V3A** [comment]
Not enough info! Please post more details with *OS, info, versions* with *screenshots* and *commands* + (text) *output* leading up to the issue. Otherwise close this.

**Comment by pzybinska** [comment]
Sorry for the lack of info!

Specs:
Windows 10
Miniconda Python 3.7
Git version 2.26.2
GeForce 1070 Ti
Cuda 9.0
cuDNN 7.4.2

After running scripts\install_windows.bat I get this ERROR:
![astroid](https://user-images.githubusercontent.com/48999145/80024301-1ef27100-84df-11ea-96ab-5e13734a233e.PNG)
Installing wrapt and six manually doesn't do anything.

When running run_windows.bat
![output](https://user-images.githubusercontent.com/48999145/80022732-c8843300-84dc-11ea-823b-0bb2af9e37a5.PNG)

**Comment by alievk** [comment]
```
conda activate avatarify
pip show opencv-python
```
what is the output?

**Comment by pzybinska** [comment]
![cv](https://user-images.githubusercontent.com/48999145/80027079-772b7200-84e3-11ea-8191-c1c85ff28fdf.PNG)

**Comment by alievk** [comment]
That's weird. What is the python version?
```
conda activate avatarify
python --version
```

**Comment by mmollet** [comment]
i have the very same problem...

![grafik](https://user-images.githubusercontent.com/23624994/81049850-4bcf5c80-8ebf-11ea-843f-b570dab7fefb.png)

**Comment by alievk** [comment]
What if you downgrade opencv?

```
pip install opencv-python==3.4.9.33
```

Relevant [link](https://stackoverflow.com/a/54321350)

**Comment by mmollet** [comment]
Installating the WIndows Media Stuff fixed the error for me because i have a N Version installed.

**Comment by alievk** [comment]
@mmollet could you describe that in detail for other people?

**Comment by mmollet** [comment]
sure, first i did this 

conda activate avatarify
pip install opencv-python==3.4.9.33

then i did this:
https://www.microsoft.com/en-us/software-download/mediafeaturepack
ive used version 1903, downloaded, installed, rebooted and after run_windows.bat was working.

**Comment by alievk** [comment]
@mmollet did you check whether the first step is enough?

**Comment by madams1337** [comment]
> @mmollet did you check whether the first step is enough?

@alievk I checked. First step is actually not relevant. opencv-python==4.2.0 also works.

> sure, first i did this
> 
> conda activate avatarify
> pip install opencv-python==3.4.9.33
> 
> then i did this:
> https://www.microsoft.com/en-us/software-download/mediafeaturepack
> ive used version 1903, downloaded, installed, rebooted and after run_windows.bat was working.

Installing the mediafeaturepack is mandatory, since upgrading to Windows Version 1909 could've deleted previously installed feature packs. So @mmollet second step is the important one.

**Comment by JohanAR** [comment]
Is still relevant? If so, maybe the installation of mediafeaturepack should be added to the README?

**Comment by wangyr520** [comment]
Hello,alievk
What's the trouble?How to fix it?
thanks b/r
------------------------------------------------------------------------------------------------------
(avatarify) C:\Users\Administrator\avatarify>run_windows.bat
[1637234365.135559] Loading Predictor
Traceback (most recent call last):
  File "afy/cam_fomm.py", line 216, in <module>
    from afy import predictor_local
  File "C:\Users\Administrator\avatarify\afy\predictor_local.py", line 4, in <module>
    from modules.keypoint_detector import KPDetector
ModuleNotFoundError: No module named 'modules'
---------------------------------------------------------------------------------------------------

**Comment by Lisahocker** [comment]
im having isseus  
OMP: Error #15: Initializing libiomp5md.dll, but found libiomp5md.dll already initialized.

**Comment by nickleo-cmd** [comment]
> ## Hello,alievk
> What's the trouble?How to fix it?
> thanks b/r
> ## (avatarify) C:\Users\Administrator\avatarify>run_windows.bat
> [1637234365.135559] Loading Predictor
> Traceback (most recent call last):
> File "afy/cam_fomm.py", line 216, in
> from afy import predictor_local
> File "C:\Users\Administrator\avatarify\afy\predictor_local.py", line 4, in
> from modules.keypoint_detector import KPDetector
> ModuleNotFoundError: No module named 'modules'

Hello, have you been able to resolve issues because i have similar issue

**Comment by godsplangiftportal** [comment]
Hello I’m always  having issue at this point after the third code on windows installation 
![Uploading 3957BA1A-1C7C-4AB4-8611-3D58B90A72DD.jpeg…]()

**Comment by Talkvibes** [comment]
(avatarify) C:\Users\oluwa\avatarify-python>run_windows.bat
[1691226719.616641] Loading Predictor
Traceback (most recent call last):
  File "afy/cam_fomm.py", line 216, in <module>
    from afy import predictor_local
  File "C:\Users\oluwa\avatarify-python\afy\predictor_local.py", line 8, in <module>
    import face_alignment
  File "C:\ProgramData\miniconda3\envs\avatarify\lib\site-packages\face_alignment\__init__.py", line 7, in <module>
    from .api import FaceAlignment, LandmarksType, NetworkSize
  File "C:\ProgramData\miniconda3\envs\avatarify\lib\site-packages\face_alignment\api.py", line 4, in <module>
    from skimage import io
  File "C:\ProgramData\miniconda3\envs\avatarify\lib\site-packages\skimage\_shared\lazy.py", line 62, in __getattr__
    return importlib.import_module(f'{package_name}.{name}')
  File "C:\ProgramData\miniconda3\envs\avatarify\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\ProgramData\miniconda3\envs\avatarify\lib\site-packages\skimage\io\__init__.py", line 7, in <module>
    from .manage_plugins import *
  File "C:\ProgramData\miniconda3\envs\avatarify\lib\site-packages\skimage\io\manage_plugins.py", line 23, in <module>
    from .collection import imread_collection_wrapper
  File "C:\ProgramData\miniconda3\envs\avatarify\lib\site-packages\skimage\io\collection.py", line 12, in <module>
    from PIL import Image, __version__ as pil_version
  File "C:\ProgramData\miniconda3\envs\avatarify\lib\site-packages\PIL\Image.py", line 100, in <module>
    from . import _imaging as core
ImportError: DLL load failed: The specified module could not be found.

**Comment by badmuspro** [comment]
Please open this issues I’m having the same problem after I follow the steps correctly 
I’m using window 11
![IMG_5573](https://github.com/alievk/avatarify-python/assets/87235461/f67b4438-27ea-413d-a73f-c4d80f59dcf6)

**Comment by SanPatrick01** [comment]
Pip install pillow==9.0.0

**Comment by niklaus699** [comment]
(avatarify) C:\Users\HP\avatarify-python>run_windows.bat
[1722502467.831207] Loading Predictor
Traceback (most recent call last):
  File "afy/cam_fomm.py", line 216, in <module>
    from afy import predictor_local
  File "C:\Users\HP\avatarify-python\afy\predictor_local.py", line 8, in <module>
    import face_alignment
  File "C:\Users\HP\miniconda3\envs\avatarify\lib\site-packages\face_alignment\__init__.py", line 7, in <module>
    from .api import FaceAlignment, LandmarksType, NetworkSize
  File "C:\Users\HP\miniconda3\envs\avatarify\lib\site-packages\face_alignment\api.py", line 4, in <module>
    from skimage import io
  File "C:\Users\HP\miniconda3\envs\avatarify\lib\site-packages\skimage\_shared\lazy.py", line 62, in __getattr__
    return importlib.import_module(f'{package_name}.{name}')
  File "C:\Users\HP\miniconda3\envs\avatarify\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\HP\miniconda3\envs\avatarify\lib\site-packages\skimage\io\__init__.py", line 7, in <module>
    from .manage_plugins import *
  File "C:\Users\HP\miniconda3\envs\avatarify\lib\site-packages\skimage\io\manage_plugins.py", line 23, in <module>
    from .collection import imread_collection_wrapper
  File "C:\Users\HP\miniconda3\envs\avatarify\lib\site-packages\skimage\io\collection.py", line 12, in <module>
    from PIL import Image, __version__ as pil_version
  File "C:\Users\HP\miniconda3\envs\avatarify\lib\site-packages\PIL\Image.py", line 100, in <module>
    from . import _imaging as core
ImportError: DLL load failed: The specified module could not be found.



Please help i am having this issue please its urgent.
