### ISSUE TITLE
Installation error on Manjaro

### ISSUE THREAD

**Issue by roukmoute** [alievk/avatarify-python#181]
**Describe the bug**
Here it is my log:
```sh
~/workspace/avatarify  master ✔                                                                                                                                                     3d  ⍉
▶ bash scripts/install.sh
Clonage dans 'v4l2loopback'...
remote: Enumerating objects: 111, done.
remote: Counting objects: 100% (111/111), done.
remote: Compressing objects: 100% (67/67), done.
remote: Total 1817 (delta 58), reused 82 (delta 38), pack-reused 1706
Réception d'objets: 100% (1817/1817), 822.66 Kio | 1.80 Mio/s, fait.
Résolution des deltas: 100% (1021/1021), fait.
--- Installing v4l2loopback (sudo privelege required)
Building v4l2-loopback driver...
make -C /lib/modules/`uname -r`/build M=/home/roukmoute/workspace/avatarify/v4l2loopback modules
make[1]: *** /lib/modules/5.4.28-rt19-MANJARO/build : Aucun fichier ou dossier de ce type. Arrêt.
make: *** [Makefile:43 : v4l2loopback.ko] Erreur 2
[sudo] Mot de passe de roukmoute : 
depmod: ERROR: could not open directory /lib/modules/5.4.28-rt19-MANJARO: No such file or directory
depmod: FATAL: could not search modules: No such file or directory
scripts/install.sh: ligne 20: /usr/etc/profile.d/conda.sh: Aucun fichier ou dossier de ce type
Collecting package metadata (current_repodata.json): failed

NotWritableError: The current user does not have write permissions to a required path.
  path: /usr/pkgs/urls.txt
  uid: 1000
  gid: 1001

If you feel that permissions on this path are set incorrectly, you can manually
change them by executing

  $ sudo chown 1000:1001 /usr/pkgs/urls.txt

In general, it's not advisable to use 'sudo conda'.



CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.



NoBaseEnvironmentError: This conda installation has no default base environment. Use
'conda create' to create new environments and 'conda activate' to
activate environments.



NoBaseEnvironmentError: This conda installation has no default base environment. Use
'conda create' to create new environments and 'conda activate' to
activate environments.


Clonage dans 'fomm'...
remote: Enumerating objects: 11, done.
remote: Counting objects: 100% (11/11), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 211 (delta 3), reused 6 (delta 2), pack-reused 200
Réception d'objets: 100% (211/211), 58.17 Mio | 18.61 Mio/s, fait.
Résolution des deltas: 100% (102/102), fait.
Defaulting to user installation because normal site-packages is not writeable
Collecting cloudpickle==0.5.3
  Downloading cloudpickle-0.5.3-py2.py3-none-any.whl (13 kB)
Collecting cycler==0.10.0
  Downloading cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
Collecting dask==0.18.2
  Downloading dask-0.18.2-py2.py3-none-any.whl (645 kB)
     |████████████████████████████████| 645 kB 5.2 MB/s 
Collecting decorator==4.3.0
  Downloading decorator-4.3.0-py2.py3-none-any.whl (9.2 kB)
Collecting imageio==2.3.0
  Downloading imageio-2.3.0-py2.py3-none-any.whl (3.3 MB)
     |████████████████████████████████| 3.3 MB 10.4 MB/s 
Collecting kiwisolver==1.0.1
  Downloading kiwisolver-1.0.1.tar.gz (31 kB)
Collecting matplotlib==2.2.2
  Downloading matplotlib-2.2.2.tar.gz (37.3 MB)
     |████████████████████████████████| 37.3 MB 19.5 MB/s 
Collecting networkx==2.1
  Downloading networkx-2.1.zip (1.6 MB)
     |████████████████████████████████| 1.6 MB 26.2 MB/s 
Collecting numpy==1.15.0
  Downloading numpy-1.15.0.zip (4.5 MB)
     |████████████████████████████████| 4.5 MB 70.3 MB/s 
Collecting pandas==0.23.4
  Downloading pandas-0.23.4.tar.gz (10.5 MB)
     |████████████████████████████████| 10.5 MB 23.9 MB/s 
Collecting Pillow==6.2.2
  Downloading Pillow-6.2.2-cp38-cp38-manylinux1_x86_64.whl (2.1 MB)
     |████████████████████████████████| 2.1 MB 25.6 MB/s 
Collecting pycparser==2.18
  Downloading pycparser-2.18.tar.gz (245 kB)
     |████████████████████████████████| 245 kB 5.2 MB/s 
Collecting pygit==0.1
  Downloading pygit-0.1.tar.gz (6.7 kB)
Collecting pyparsing==2.2.0
  Downloading pyparsing-2.2.0-py2.py3-none-any.whl (56 kB)
     |████████████████████████████████| 56 kB 6.0 MB/s 
Collecting python-dateutil==2.7.3
  Downloading python_dateutil-2.7.3-py2.py3-none-any.whl (211 kB)
     |████████████████████████████████| 211 kB 19.7 MB/s 
Collecting pytz==2018.5
  Downloading pytz-2018.5-py2.py3-none-any.whl (510 kB)
     |████████████████████████████████| 510 kB 28.0 MB/s 
Collecting PyWavelets==0.5.2
  Downloading PyWavelets-0.5.2.tar.gz (4.4 MB)
     |████████████████████████████████| 4.4 MB 22.2 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-1fscbyb5/PyWavelets/setup.py'"'"'; __file__='"'"'/tmp/pip-install-1fscbyb5/PyWavelets/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-1fscbyb5/PyWavelets/pip-egg-info
         cwd: /tmp/pip-install-1fscbyb5/PyWavelets/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-1fscbyb5/PyWavelets/setup.py", line 12, in <module>
        from numpy import get_include as get_numpy_include
    ModuleNotFoundError: No module named 'numpy'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Info (please complete the following information):**
 - OS (e.g., Linux): `Linux roukmoute-pc 5.4.28-rt19-MANJARO #1 SMP PREEMPT_RT Mon Mar 30 19:49:56 UTC 2020 x86_64 GNU/Linux`
 - GPU model: 
```
~/workspace/avatarify  master ✗                                                                                                                                                   3d ◒  ⍉
▶ nvidia-smi -L
NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.
```

**Comment by alievk** [comment]
It complains that conda doesn't have an access to `/usr/pkgs/urls.txt`
```
NotWritableError: The current user does not have write permissions to a required path.
  path: /usr/pkgs/urls.txt
  uid: 1000
  gid: 1001
```

It also says you can manually change the permissions:
```
If you feel that permissions on this path are set incorrectly, you can manually
change them by executing

$ sudo chown 1000:1001 /usr/pkgs/urls.txt
```

Another problem is `v4l2loopback` failed to build, but let's focus on the `conda` issue first.

**Comment by roukmoute** [comment]
In fact the file doesn't exist.

```sh
~/workspace/avatarify  master ✗
▶ sudo chown 1000:1001 /usr/pkgs/urls.txt
chown: Cannot access '/usr/pkgs/urls.txt': No files or folders of this type.
```

**Comment by roukmoute** [comment]
Ok I've create the folder, the file and with right rights.

```sh
~/workspace/avatarify  master ✗                                                                                                                                                    7d ◒  
▶ bash scripts/install.sh                
                         
Clonage dans 'v4l2loopback'...
remote: Enumerating objects: 111, done.
remote: Counting objects: 100% (111/111), done.
remote: Compressing objects: 100% (67/67), done.
remote: Total 1817 (delta 58), reused 82 (delta 38), pack-reused 1706
Réception d'objets: 100% (1817/1817), 822.66 Kio | 2.22 Mio/s, fait.
Résolution des deltas: 100% (1021/1021), fait.
--- Installing v4l2loopback (sudo privelege required)
Building v4l2-loopback driver...
make -C /lib/modules/`uname -r`/build M=/home/roukmoute/workspace/avatarify/v4l2loopback modules
make[1] : on entre dans le répertoire « /usr/lib/modules/5.4.39-rt23-MANJARO/build »
  CC [M]  /home/roukmoute/workspace/avatarify/v4l2loopback/v4l2loopback.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC [M]  /home/roukmoute/workspace/avatarify/v4l2loopback/v4l2loopback.mod.o
  LD [M]  /home/roukmoute/workspace/avatarify/v4l2loopback/v4l2loopback.ko
make[1] : on quitte le répertoire « /usr/lib/modules/5.4.39-rt23-MANJARO/build »
make -C /lib/modules/`uname -r`/build M=/home/roukmoute/workspace/avatarify/v4l2loopback modules_install
make[1] : on entre dans le répertoire « /usr/lib/modules/5.4.39-rt23-MANJARO/build »
  INSTALL /home/roukmoute/workspace/avatarify/v4l2loopback/v4l2loopback.ko
At main.c:160:
- SSL error:02001002:system library:fopen:No such file or directory: crypto/bio/bss_file.c:69
- SSL error:2006D080:BIO routines:BIO_new_file:no such file: crypto/bio/bss_file.c:76
sign-file: certs/signing_key.pem: No such file or directory
  DEPMOD  5.4.39-rt23-MANJARO
make[1] : on quitte le répertoire « /usr/lib/modules/5.4.39-rt23-MANJARO/build »

SUCCESS (if you got 'SSL errors' above, you can safely ignore them)

scripts/install.sh: ligne 20: /usr/etc/profile.d/conda.sh: Aucun fichier ou dossier de ce type
Collecting package metadata (current_repodata.json): failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/usr/lib/python3.8/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/usr/lib/python3.8/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/usr/lib/python3.8/site-packages/conda/cli/conda_argparse.py", line 82, in do_call
        return getattr(module, func_name)(args, parser)
      File "/usr/lib/python3.8/site-packages/conda/cli/main_create.py", line 37, in execute
        install(args, parser, 'create')
      File "/usr/lib/python3.8/site-packages/conda/cli/install.py", line 261, in install
        unlink_link_transaction = solver.solve_for_transaction(
      File "/usr/lib/python3.8/site-packages/conda/core/solve.py", line 114, in solve_for_transaction
        unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
      File "/usr/lib/python3.8/site-packages/conda/core/solve.py", line 157, in solve_for_diff
        final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
      File "/usr/lib/python3.8/site-packages/conda/core/solve.py", line 262, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
      File "/usr/lib/python3.8/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/usr/lib/python3.8/site-packages/conda/core/solve.py", line 415, in _collect_all_metadata
        index, r = self._prepare(prepared_specs)
      File "/usr/lib/python3.8/site-packages/conda/core/solve.py", line 1010, in _prepare
        reduced_index = get_reduced_index(self.prefix, self.channels,
      File "/usr/lib/python3.8/site-packages/conda/core/index.py", line 227, in get_reduced_index
        new_records = SubdirData.query_all(spec, channels=channels, subdirs=subdirs,
      File "/usr/lib/python3.8/site-packages/conda/core/subdir_data.py", line 83, in query_all
        create_cache_dir()
      File "/usr/lib/python3.8/site-packages/conda/core/subdir_data.py", line 660, in create_cache_dir
        mkdir_p_sudo_safe(cache_dir)
      File "/usr/lib/python3.8/site-packages/conda/gateways/disk/__init__.py", line 84, in mkdir_p_sudo_safe
        os.mkdir(path)
    PermissionError: [Errno 13] Permission denied: '/usr/pkgs/cache'

`$ /usr/sbin/conda create -y -n avatarify python=3.7`

  environment variables:
                 CIO_TEST=<not set>
                CONDA_EXE=/usr/bin/conda
               CONDA_ROOT=/usr
              CONDA_SHLVL=0
          MOZ_PLUGIN_PATH=/usr/lib/mozilla/plugins
                     PATH=/usr/lib/x86_64-linux-gnu/qt4/bin:/usr/local/sbin:/usr/local/bin:/usr/
                          sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/roukmoute/b
                          in:/home/roukmoute/bin:/usr/local/bin:/home/roukmoute/adr-tools/src:/h
                          ome/roukmoute/.local/bin:/usr/condabin:/usr/local/bin:/usr/bin:/bin:/u
                          sr/local/sbin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/ven
                          dor_perl:/usr/bin/core_perl:/home/roukmoute/.bin:/home/roukmoute/.gem/
                          ruby/2.7.0/bin:/home/roukmoute/.fzf/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
            XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
         XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0

     active environment : None
            shell level : 0
       user config file : /home/roukmoute/.condarc
 populated config files : 
          conda version : 4.8.3
    conda-build version : not installed
         python version : 3.8.2.final.0
       virtual packages : __glibc=2.31
       base environment : /usr  (read only)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /usr/pkgs
                          /home/roukmoute/.conda/pkgs
       envs directories : /home/roukmoute/.conda/envs
                          /usr/envs
               platform : linux-64
             user-agent : conda/4.8.3 requests/2.23.0 CPython/3.8.2 Linux/5.4.39-rt23-MANJARO manjaro/20.0.1 glibc/2.31
                UID:GID : 1000:1001
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

Upload successful.

CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.



NoBaseEnvironmentError: This conda installation has no default base environment. Use
'conda create' to create new environments and 'conda activate' to
activate environments.



NoBaseEnvironmentError: This conda installation has no default base environment. Use
'conda create' to create new environments and 'conda activate' to
activate environments.


Clonage dans 'fomm'...
remote: Enumerating objects: 211, done.
remote: Total 211 (delta 0), reused 0 (delta 0), pack-reused 211
Réception d'objets: 100% (211/211), 58.16 Mio | 30.17 Mio/s, fait.
Résolution des deltas: 100% (108/108), fait.
Defaulting to user installation because normal site-packages is not writeable
Collecting cloudpickle==0.5.3
  Using cached cloudpickle-0.5.3-py2.py3-none-any.whl (13 kB)
Collecting cycler==0.10.0
  Using cached cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
Collecting dask==0.18.2
  Using cached dask-0.18.2-py2.py3-none-any.whl (645 kB)
Collecting decorator==4.3.0
  Using cached decorator-4.3.0-py2.py3-none-any.whl (9.2 kB)
Collecting imageio==2.3.0
  Using cached imageio-2.3.0-py2.py3-none-any.whl (3.3 MB)
Collecting kiwisolver==1.0.1
  Using cached kiwisolver-1.0.1.tar.gz (31 kB)
Collecting matplotlib==2.2.2
  Using cached matplotlib-2.2.2.tar.gz (37.3 MB)
Collecting networkx==2.1
  Using cached networkx-2.1.zip (1.6 MB)
Collecting numpy==1.15.0
  Using cached numpy-1.15.0.zip (4.5 MB)
Collecting pandas==0.23.4
  Using cached pandas-0.23.4.tar.gz (10.5 MB)
Collecting Pillow==6.2.2
  Using cached Pillow-6.2.2-cp38-cp38-manylinux1_x86_64.whl (2.1 MB)
Collecting pycparser==2.18
  Using cached pycparser-2.18.tar.gz (245 kB)
Collecting pygit==0.1
  Using cached pygit-0.1.tar.gz (6.7 kB)
Collecting pyparsing==2.2.0
  Using cached pyparsing-2.2.0-py2.py3-none-any.whl (56 kB)
Collecting python-dateutil==2.7.3
  Using cached python_dateutil-2.7.3-py2.py3-none-any.whl (211 kB)
Collecting pytz==2018.5
  Using cached pytz-2018.5-py2.py3-none-any.whl (510 kB)
Collecting PyWavelets==0.5.2
  Using cached PyWavelets-0.5.2.tar.gz (4.4 MB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-1u1jrzix/PyWavelets/setup.py'"'"'; __file__='"'"'/tmp/pip-install-1u1jrzix/PyWavelets/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-1u1jrzix/PyWavelets/pip-egg-info
         cwd: /tmp/pip-install-1u1jrzix/PyWavelets/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-1u1jrzix/PyWavelets/setup.py", line 12, in <module>
        from numpy import get_include as get_numpy_include
    ModuleNotFoundError: No module named 'numpy'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by roukmoute** [comment]
Ok I've created the folder cache and attribute the chown to all the folder pkgs.

```sh
~/workspace/avatarify  master ✔
▶ sudo mkdir -p /usr/pkgs/cache && sudo chown -R 1000:1001 /usr/pkgs/
```

So now I've this redondant error:

```sh
~/workspace/avatarify  master ✔                                                      3d  
▶ bash scripts/install.sh                                            
                         
Clonage dans 'v4l2loopback'...
remote: Enumerating objects: 111, done.
remote: Counting objects: 100% (111/111), done.
remote: Compressing objects: 100% (67/67), done.
remote: Total 1817 (delta 58), reused 82 (delta 38), pack-reused 1706
Réception d'objets: 100% (1817/1817), 822.66 Kio | 2.12 Mio/s, fait.
Résolution des deltas: 100% (1021/1021), fait.
--- Installing v4l2loopback (sudo privelege required)
Building v4l2-loopback driver...
make -C /lib/modules/`uname -r`/build M=/home/roukmoute/workspace/avatarify/v4l2loopback modules
make[1] : on entre dans le répertoire « /usr/lib/modules/5.4.39-rt23-MANJARO/build »
  CC [M]  /home/roukmoute/workspace/avatarify/v4l2loopback/v4l2loopback.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC [M]  /home/roukmoute/workspace/avatarify/v4l2loopback/v4l2loopback.mod.o
  LD [M]  /home/roukmoute/workspace/avatarify/v4l2loopback/v4l2loopback.ko
make[1] : on quitte le répertoire « /usr/lib/modules/5.4.39-rt23-MANJARO/build »
[sudo] Mot de passe de roukmoute : 
make -C /lib/modules/`uname -r`/build M=/home/roukmoute/workspace/avatarify/v4l2loopback modules_install
make[1] : on entre dans le répertoire « /usr/lib/modules/5.4.39-rt23-MANJARO/build »
  INSTALL /home/roukmoute/workspace/avatarify/v4l2loopback/v4l2loopback.ko
At main.c:160:
- SSL error:02001002:system library:fopen:No such file or directory: crypto/bio/bss_file.c:69
- SSL error:2006D080:BIO routines:BIO_new_file:no such file: crypto/bio/bss_file.c:76
sign-file: certs/signing_key.pem: No such file or directory
  DEPMOD  5.4.39-rt23-MANJARO
make[1] : on quitte le répertoire « /usr/lib/modules/5.4.39-rt23-MANJARO/build »

SUCCESS (if you got 'SSL errors' above, you can safely ignore them)

scripts/install.sh: ligne 20: /usr/etc/profile.d/conda.sh: Aucun fichier ou dossier de ce type
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/roukmoute/.conda/envs/avatarify

  added / updated specs:
    - python=3.7


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    _libgcc_mutex-0.1          |             main           3 KB
    ca-certificates-2020.1.1   |                0         125 KB
    certifi-2020.4.5.1         |           py37_0         155 KB
    ld_impl_linux-64-2.33.1    |       h53a641e_7         568 KB
    libedit-3.1.20181209       |       hc058e9b_0         163 KB
    libffi-3.3                 |       he6710b0_1          50 KB
    libgcc-ng-9.1.0            |       hdf63c60_0         5.1 MB
    libstdcxx-ng-9.1.0         |       hdf63c60_0         3.1 MB
    ncurses-6.2                |       he6710b0_1         817 KB
    openssl-1.1.1g             |       h7b6447c_0         2.5 MB
    pip-20.0.2                 |           py37_3         1.7 MB
    python-3.7.7               |       hcff3b4d_5        45.1 MB
    readline-8.0               |       h7b6447c_0         356 KB
    setuptools-46.4.0          |           py37_0         514 KB
    sqlite-3.31.1              |       h62c20be_1         1.1 MB
    tk-8.6.8                   |       hbc83047_0         2.8 MB
    wheel-0.34.2               |           py37_0          51 KB
    xz-5.2.5                   |       h7b6447c_0         341 KB
    zlib-1.2.11                |       h7b6447c_3         103 KB
    ------------------------------------------------------------
                                           Total:        64.6 MB

The following NEW packages will be INSTALLED:

  _libgcc_mutex      pkgs/main/linux-64::_libgcc_mutex-0.1-main
  ca-certificates    pkgs/main/linux-64::ca-certificates-2020.1.1-0
  certifi            pkgs/main/linux-64::certifi-2020.4.5.1-py37_0
  ld_impl_linux-64   pkgs/main/linux-64::ld_impl_linux-64-2.33.1-h53a641e_7
  libedit            pkgs/main/linux-64::libedit-3.1.20181209-hc058e9b_0
  libffi             pkgs/main/linux-64::libffi-3.3-he6710b0_1
  libgcc-ng          pkgs/main/linux-64::libgcc-ng-9.1.0-hdf63c60_0
  libstdcxx-ng       pkgs/main/linux-64::libstdcxx-ng-9.1.0-hdf63c60_0
  ncurses            pkgs/main/linux-64::ncurses-6.2-he6710b0_1
  openssl            pkgs/main/linux-64::openssl-1.1.1g-h7b6447c_0
  pip                pkgs/main/linux-64::pip-20.0.2-py37_3
  python             pkgs/main/linux-64::python-3.7.7-hcff3b4d_5
  readline           pkgs/main/linux-64::readline-8.0-h7b6447c_0
  setuptools         pkgs/main/linux-64::setuptools-46.4.0-py37_0
  sqlite             pkgs/main/linux-64::sqlite-3.31.1-h62c20be_1
  tk                 pkgs/main/linux-64::tk-8.6.8-hbc83047_0
  wheel              pkgs/main/linux-64::wheel-0.34.2-py37_0
  xz                 pkgs/main/linux-64::xz-5.2.5-h7b6447c_0
  zlib               pkgs/main/linux-64::zlib-1.2.11-h7b6447c_3



Downloading and Extracting Packages
xz-5.2.5             | 341 KB    | ############################################### | 100% 
certifi-2020.4.5.1   | 155 KB    | ############################################### | 100% 
ld_impl_linux-64-2.3 | 568 KB    | ############################################### | 100% 
_libgcc_mutex-0.1    | 3 KB      | ############################################### | 100% 
pip-20.0.2           | 1.7 MB    | ############################################### | 100% 
libedit-3.1.20181209 | 163 KB    | ############################################### | 100% 
readline-8.0         | 356 KB    | ############################################### | 100% 
wheel-0.34.2         | 51 KB     | ############################################### | 100% 
libffi-3.3           | 50 KB     | ############################################### | 100% 
ncurses-6.2          | 817 KB    | ############################################### | 100% 
openssl-1.1.1g       | 2.5 MB    | ############################################### | 100% 
zlib-1.2.11          | 103 KB    | ############################################### | 100% 
libgcc-ng-9.1.0      | 5.1 MB    | ############################################### | 100% 
setuptools-46.4.0    | 514 KB    | ############################################### | 100% 
python-3.7.7         | 45.1 MB   | ############################################### | 100% 
ca-certificates-2020 | 125 KB    | ############################################### | 100% 
libstdcxx-ng-9.1.0   | 3.1 MB    | ############################################### | 100% 
tk-8.6.8             | 2.8 MB    | ############################################### | 100% 
sqlite-3.31.1        | 1.1 MB    | ############################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate avatarify
#
# To deactivate an active environment, use
#
#     $ conda deactivate


CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.



NoBaseEnvironmentError: This conda installation has no default base environment. Use
'conda create' to create new environments and 'conda activate' to
activate environments.



NoBaseEnvironmentError: This conda installation has no default base environment. Use
'conda create' to create new environments and 'conda activate' to
activate environments.


Clonage dans 'fomm'...
remote: Enumerating objects: 211, done.
remote: Total 211 (delta 0), reused 0 (delta 0), pack-reused 211
Réception d'objets: 100% (211/211), 58.16 Mio | 29.97 Mio/s, fait.
Résolution des deltas: 100% (108/108), fait.
Defaulting to user installation because normal site-packages is not writeable
Collecting cloudpickle==0.5.3
  Using cached cloudpickle-0.5.3-py2.py3-none-any.whl (13 kB)
Collecting cycler==0.10.0
  Using cached cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
Collecting dask==0.18.2
  Using cached dask-0.18.2-py2.py3-none-any.whl (645 kB)
Collecting decorator==4.3.0
  Using cached decorator-4.3.0-py2.py3-none-any.whl (9.2 kB)
Collecting imageio==2.3.0
  Using cached imageio-2.3.0-py2.py3-none-any.whl (3.3 MB)
Collecting kiwisolver==1.0.1
  Using cached kiwisolver-1.0.1.tar.gz (31 kB)
Collecting matplotlib==2.2.2
  Using cached matplotlib-2.2.2.tar.gz (37.3 MB)
Collecting networkx==2.1
  Using cached networkx-2.1.zip (1.6 MB)
Collecting numpy==1.15.0
  Using cached numpy-1.15.0.zip (4.5 MB)
Collecting pandas==0.23.4
  Using cached pandas-0.23.4.tar.gz (10.5 MB)
Collecting Pillow==6.2.2
  Using cached Pillow-6.2.2-cp38-cp38-manylinux1_x86_64.whl (2.1 MB)
Collecting pycparser==2.18
  Using cached pycparser-2.18.tar.gz (245 kB)
Collecting pygit==0.1
  Using cached pygit-0.1.tar.gz (6.7 kB)
Collecting pyparsing==2.2.0
  Using cached pyparsing-2.2.0-py2.py3-none-any.whl (56 kB)
Collecting python-dateutil==2.7.3
  Using cached python_dateutil-2.7.3-py2.py3-none-any.whl (211 kB)
Collecting pytz==2018.5
  Using cached pytz-2018.5-py2.py3-none-any.whl (510 kB)
Collecting PyWavelets==0.5.2
  Using cached PyWavelets-0.5.2.tar.gz (4.4 MB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-bzq2ob2_/PyWavelets/setup.py'"'"'; __file__='"'"'/tmp/pip-install-bzq2ob2_/PyWavelets/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-bzq2ob2_/PyWavelets/pip-egg-info
         cwd: /tmp/pip-install-bzq2ob2_/PyWavelets/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-bzq2ob2_/PyWavelets/setup.py", line 12, in <module>
        from numpy import get_include as get_numpy_include
    ModuleNotFoundError: No module named 'numpy'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by alievk** [comment]
I see several conda issues. Sorry I'm not a Manjaro user, can't help much here. But what you can try is to install it manually running the commands one by one from the `install.sh` script. You can also try using `venv` instead of `conda` if this could help.

**Comment by romulowspp** [comment]
I solved this problem using kernel 419 and installing kernel-headers package.

**Comment by JohanAR** [comment]
Still having problems installing? If you are, maybe using the docker version of Avatarify would be easier

**Comment by roukmoute** [comment]
Yes but there is no official version of Avatarify (https://hub.docker.com/search?q=Avatarify&type=image).

**Comment by JohanAR** [comment]
Not pre-built, but it comes with scripts to build your own image, [see this section](https://github.com/alievk/avatarify-python/tree/master/docs#docker) and then start it like this:

`./run.sh --docker
`
