### ISSUE TITLE
run_windows.bat raises a RuntimeError

### ISSUE THREAD

**Issue by Yoto3525** [alievk/avatarify-python#396]
Traceback (most recent call last):
  File "afy/cam_fomm.py", line 218, in <module>
    **predictor_args
  File "C:\Users\Администратор\avatarify\afy\predictor_local.py", line 49, in __init__
    self.fa = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D, flip_input=True, device=self.device)
  File "C:\ProgramData\Miniconda3\envs\avatarify\lib\site-packages\face_alignment\api.py", line 83, in __init__
    load_file_from_url(models_urls.get(pytorch_version, default_model_urls)[network_name]))
  File "C:\ProgramData\Miniconda3\envs\avatarify\lib\site-packages\torch\jit\_serialization.py", line 161, in load
    cpp_module = torch._C.import_ir_module(cu, f, map_location, _extra_files)
RuntimeError: open file failed, file path: C:\Users\Администратор/.cache\torch\hub\checkpoints\2DFAN4-cd938726ad.zip

**Comment by JohanAR** [comment]
There have been reports of problems with Cyrillic letters in the file path, could be related to that.. Not sure if there is any solution or workaround at the moment
