### ISSUE TITLE
MAC [1618896898.219199] Loading Predictor.....

### ISSUE THREAD

**Issue by Roadster** [alievk/avatarify-python#404]
just one log entry: 
[1618896898.219199] Loading Predictor
all other logs are empty:

my last terminal records are:
..any thoughts? (beside removing osx)?

thanks in advance
der mischa

Last login: Tue Apr 20 07:14:27 on ttys000
(base) mischa@Mischas-MBP ~ % cd downloads
(base) mischa@Mischas-MBP downloads % cd avatarify-python-master
(base) mischa@Mischas-MBP avatarify-python-master % run_mac.sh --is-client --in-addr {in_addr} --out-addr {out_addr}
zsh: command not found: run_mac.sh
(base) mischa@Mischas-MBP avatarify-python-master % ls          
Dockerfile		avatars			run.sh
LICENSE.md		config.yaml		run_mac.sh
README.md		docs			run_windows.bat
afy			requirements.txt	scripts
avatarify.ipynb		requirements_client.txt	var
(base) mischa@Mischas-MBP avatarify-python-master % ./run_mac.sh --is-client --in-addr {in_addr} --out-addr {out_addr}
[1618896898.219249] Loading Predictor
Process send_process:
Traceback (most recent call last):
  File "/Users/mischa/opt/miniconda3/envs/avatarify/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/Users/mischa/opt/miniconda3/envs/avatarify/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/mischa/Downloads/avatarify-python-master/afy/predictor_remote.py", line 134, in send_worker
    sender.connect(address)
  File "zmq/backend/cython/socket.pyx", line 583, in zmq.backend.cython.socket.Socket.connect
  File "zmq/backend/cython/checkrc.pxd", line 26, in zmq.backend.cython.checkrc._check_rc
Process recv_process:
zmq.error.ZMQError: Invalid argument
Traceback (most recent call last):
  File "/Users/mischa/opt/miniconda3/envs/avatarify/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/Users/mischa/opt/miniconda3/envs/avatarify/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/mischa/Downloads/avatarify-python-master/afy/predictor_remote.py", line 170, in recv_worker
    receiver.connect(address)
  File "zmq/backend/cython/socket.pyx", line 583, in zmq.backend.cython.socket.Socket.connect
  File "zmq/backend/cython/checkrc.pxd", line 26, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Invalid argument
s/mischa/opt/miniconda3/envs/avatarify/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/Users/mischa/opt/miniconda3/envs/avatarify/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/mischa/Downloads/avatarify-python-master/afy/predictor_remote.py", line 134, in send_worker
    sender.connect(address)
  File "zmq/backend/cython/socket.pyx", line 583, in zmq.backend.cython.socket.Socket.connect
  File "zmq/backend/cython/checkrc.pxd", line 26, in zmq.backend.cython.checkrc._check_rc
Process recv_process:
zmq.error.ZMQError: Invalid argument
Traceback (most recent call last):
  File "/Users/mischa/opt/miniconda3/envs/avatarify/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/Users/mischa/opt/miniconda3/envs/avatarify/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/mischa/Downl

**Comment by JohanAR** [comment]
You're supposed to replace {in_addr} and {out_addr} with the addresses where you are running the server

**Comment by Roadster** [comment]
> You're supposed to replace {in_addr} and {out_addr} with the addresses where you are running the server

Ahaaa :-) thx (nearly)... sorry if that was a "silly question" however - i skipped the AWS cloud part -> now i try with my ngrok tunnel (still not sure if it should be the mapped port (eg: .tcp://4.tcp.eu.ngrok.io:18965) or the target port as shown in the logs :5557)

**Comment by JohanAR** [comment]
Sorry, I've never tried running Avatarify as client/server so I don't know that.. but good luck! :)

**Comment by shehrum** [comment]
Hi, were you able to solve this?

**Comment by Bgzoma** [comment]
Make sure your terminal is closed
Run all the codes one after the other on the colab
Till you reach the AWS Proxy. Skip there
After skipping the aws proxy. 
Run the 
# Open reverse ssh tunnel (uncomment line below)
# !./scripts/open_tunnel_ssh.sh key_pair.pem

Then you can now open the terminal.
cd avatarify

Come back to the colab and Print
print('Copy-paste to the terminal the command below and run (press Enter)\n')
print('Mac:')
print(f'./run_mac.sh --is-client --in-addr {in_addr} --out-addr {out_addr}')
print('\nWindows:')
print(f'run_windows.bat --is-client --in-addr {in_addr} --out-addr {out_addr}')
print('\nLinux:')
print(f'./run.sh --is-client --in-addr {in_addr} --out-addr {out_addr}')

When you're done printing, it'll display the code below. 

Copy the code for your default device be it linux, windows, mac as it may be and paste in the terminal.
