### ISSUE TITLE
Linux. ERROR: '''Exception: frame height does not match the height of webcam device: 720!=480'''

### ISSUE THREAD

**Issue by 00-hidan-00** [alievk/avatarify-python#419]
![изображение](https://user-images.githubusercontent.com/76614763/129123830-6809df40-b09d-4085-aaf5-81682673c247.png)

 - OS: Linux 
 - GPU model: NVIDIA GeForce GTX 1050

'''Warning: No faces were detected.
/home/admin/miniconda3/envs/avatarify/lib/python3.7/site-packages/torch/nn/functional.py:3982: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  "Default grid_sample and affine_grid behavior has changed "
/home/admin/miniconda3/envs/avatarify/lib/python3.7/site-packages/torch/nn/functional.py:1805: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
Traceback (most recent call last):
  File "afy/cam_fomm.py", line 469, in <module>
    stream.schedule_frame(out)
  File "/home/admin/miniconda3/envs/avatarify/lib/python3.7/site-packages/pyfakewebcam/pyfakewebcam.py", line 68, in schedule_frame
    raise Exception('frame height does not match the height of webcam device: {}!={}\n'.format(self._settings.fmt.pix.height, frame.shape[0]))
Exception: frame height does not match the height of webcam device: 720!=480'''

Hello. We start avatarify and everything starts normally, I press X, the "cam" window appears and everything hangs and shows such an error. Please tell me how to fix it. Thank you very much in advance.

**Comment by 00-hidan-00** [comment]
> ![изображение](https://user-images.githubusercontent.com/76614763/129123830-6809df40-b09d-4085-aaf5-81682673c247.png)
> 
>     * OS: Linux
> 
>     * GPU model: NVIDIA GeForce GTX 1050
> 
> 
> '''Warning: No faces were detected.
> /home/admin/miniconda3/envs/avatarify/lib/python3.7/site-packages/torch/nn/functional.py:3982: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
> "Default grid_sample and affine_grid behavior has changed "
> /home/admin/miniconda3/envs/avatarify/lib/python3.7/site-packages/torch/nn/functional.py:1805: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
> warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
> Traceback (most recent call last):
> File "afy/cam_fomm.py", line 469, in
> stream.schedule_frame(out)
> File "/home/admin/miniconda3/envs/avatarify/lib/python3.7/site-packages/pyfakewebcam/pyfakewebcam.py", line 68, in schedule_frame
> raise Exception('frame height does not match the height of webcam device: {}!={}\n'.format(self._settings.fmt.pix.height, frame.shape[0]))
> Exception: frame height does not match the height of webcam device: 720!=480'''
> 
> Hello. We start avatarify and everything starts normally, I press X, the "cam" window appears and everything hangs and shows such an error. Please tell me how to fix it. Thank you very much in advance.
