### ISSUE TITLE
Avatary doesn't start when I try to open it

### ISSUE THREAD

**Issue by MM5002** [alievk/avatarify-python#440]
I've just installed it but when i try to start it, the next messege appears:
Traceback (most recent call last):
  File "afy/cam_fomm.py", line 218, in <module>
    **predictor_args
  File "C:\Users\Usuario\avatarify\afy\predictor_local.py", line 49, in __init__
    self.fa = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D, flip_input=True, device=self.device)
  File "E:\Py\miniconda3\envs\avatarify\lib\site-packages\face_alignment\api.py", line 75, in __init__
    self.face_detector = face_detector_module.FaceDetector(device=device, verbose=verbose)
  File "E:\Py\miniconda3\envs\avatarify\lib\site-packages\face_alignment\detection\sfd\sfd_detector.py", line 24, in __init__
    model_weights = load_url(models_urls['s3fd'])
  File "E:\Py\miniconda3\envs\avatarify\lib\site-packages\torch\hub.py", line 555, in load_state_dict_from_url
    download_url_to_file(url, cached_file, hash_prefix, progress=progress)
  File "E:\Py\miniconda3\envs\avatarify\lib\site-packages\torch\hub.py", line 425, in download_url_to_file
    u = urlopen(req)
  File "E:\Py\miniconda3\envs\avatarify\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "E:\Py\miniconda3\envs\avatarify\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "E:\Py\miniconda3\envs\avatarify\lib\urllib\request.py", line 543, in _open
    '_open', req)
  File "E:\Py\miniconda3\envs\avatarify\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "E:\Py\miniconda3\envs\avatarify\lib\urllib\request.py", line 1393, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "E:\Py\miniconda3\envs\avatarify\lib\urllib\request.py", line 1352, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1091)>

I don't reaally know what does it mean and what x=can I do with it.

**Comment by PorthoGamesBR** [comment]
It seems that the SSL to connect to Conda is outdated. You can disable the SSL, but it may cause some security problems.
https://docs.conda.io/projects/conda/en/latest/user-guide/configuration/disable-ssl-verification.html

I read some posts and it may be a bug on a old version of Conda, so you might need to update it.
