### ISSUE TITLE
FATAL: no kernel image

### ISSUE THREAD

**Issue by j2l** [alievk/avatarify-python#441]
**Describe the bug**
Doesn't run anymore, was working for me on ubuntu 20.04

**To Reproduce**
`sudo bash run.sh`

**Info (please complete the following information):**
 - OS (e.g., Linux): Ubuntu 21.04
 - GPU model: RTX 3060

```
[1638004834.979605] Selected camera 0
Traceback (most recent call last):
  File "afy/cam_fomm.py", line 254, in <module>
    change_avatar(predictor, avatars[cur_ava])
  File "afy/cam_fomm.py", line 91, in change_avatar
    avatar_kp = predictor.get_frame_kp(new_avatar)
  File "/home/pm/Documents/github/avatarify-python-master/afy/predictor_local.py", line 114, in get_frame_kp
    kp_landmarks = self.fa.get_landmarks(image)
  File "/home/pm/miniconda3/envs/avatarify/lib/python3.7/site-packages/face_alignment/api.py", line 106, in get_landmarks
    return self.get_landmarks_from_image(image_or_path, detected_faces)
  File "/home/pm/miniconda3/envs/avatarify/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/home/pm/miniconda3/envs/avatarify/lib/python3.7/site-packages/face_alignment/api.py", line 125, in get_landmarks_from_image
    detected_faces = self.face_detector.detect_from_image(image.copy())
  File "/home/pm/miniconda3/envs/avatarify/lib/python3.7/site-packages/face_alignment/detection/sfd/sfd_detector.py", line 44, in detect_from_image
    bboxlist = detect(self.face_detector, image, device=self.device)[0]
  File "/home/pm/miniconda3/envs/avatarify/lib/python3.7/site-packages/face_alignment/detection/sfd/detect.py", line 15, in detect
    img = torch.from_numpy(img).to(device, dtype=torch.float32)
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
FATAL: exception not rethrown
run.sh: line 151: 26530 Aborted                 (core dumped) python afy/cam_fomm.py --config $FOMM_CONFIG --checkpoint $FOMM_CKPT --virt-cam $CAMID_VIRT --relative --adapt_scale $@

```

conda info
```
  active environment : avatarify
    active env location : /home/pm/miniconda3/envs/avatarify
            shell level : 2
       user config file : /home/pm/.condarc
 populated config files : 
          conda version : 4.10.3
    conda-build version : not installed
         python version : 3.7.10.final.0
       virtual packages : __cuda=11.4=0
                          __linux=5.13.0=0
                          __glibc=2.33=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/pm/miniconda3  (writable)
      conda av data dir : /home/pm/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/pm/miniconda3/pkgs
                          /home/pm/.conda/pkgs
       envs directories : /home/pm/miniconda3/envs
                          /home/pm/.conda/envs
               platform : linux-64
             user-agent : conda/4.10.3 requests/2.25.1 CPython/3.7.10 Linux/5.13.0-7620-generic pop/21.04 glibc/2.33
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

```

conda list
```
# packages in environment at /home/pm/miniconda3/envs/avatarify:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             4.5                       1_gnu  
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
blosc                     1.21.0               h9c3ff4c_0    conda-forge
brotli                    1.0.9                h9c3ff4c_4    conda-forge
brotlipy                  0.7.0           py37h5e8e339_1001    conda-forge
brunsli                   0.1                  h9c3ff4c_0    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2021.10.8            ha878542_0    conda-forge
certifi                   2021.10.8        py37h89c1867_1    conda-forge
cffi                      1.14.6           py37hc58025e_0    conda-forge
chardet                   4.0.0                    pypi_0    pypi
charls                    2.2.0                h9c3ff4c_0    conda-forge
charset-normalizer        2.0.8              pyhd8ed1ab_0    conda-forge
cloudpickle               2.0.0              pyhd8ed1ab_0    conda-forge
cryptography              3.4.7            py37h5d9358c_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
cytoolz                   0.11.0           py37h5e8e339_3    conda-forge
dask-core                 2021.11.2          pyhd8ed1ab_0    conda-forge
face-alignment            1.3.3                    pypi_0    pypi
freetype                  2.10.4               h0708190_1    conda-forge
fsspec                    2021.11.1          pyhd8ed1ab_0    conda-forge
giflib                    5.2.1                h36c2ea0_2    conda-forge
idna                      2.10                     pypi_0    pypi
imagecodecs               2021.4.28        py37hd0c323f_0    conda-forge
imageio                   2.9.0                      py_0    conda-forge
jbig                      2.1               h7f98852_2003    conda-forge
jpeg                      9d                   h36c2ea0_0    conda-forge
jxrlib                    1.1                  h7f98852_2    conda-forge
kiwisolver                1.3.1            py37h2527ec5_1    conda-forge
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.35.1               h7274673_9  
lerc                      2.2.1                h9c3ff4c_0    conda-forge
libaec                    1.0.5                h9c3ff4c_0    conda-forge
libblas                   3.9.0           11_linux64_openblas    conda-forge
libcblas                  3.9.0           11_linux64_openblas    conda-forge
libdeflate                1.7                  h7f98852_5    conda-forge
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.3.0               h5101ec6_17  
libgfortran-ng            11.2.0              h69a702a_11    conda-forge
libgfortran5              11.2.0              h5c6108e_11    conda-forge
libgomp                   9.3.0               h5101ec6_17  
liblapack                 3.9.0           11_linux64_openblas    conda-forge
libopenblas               0.3.17          pthreads_h8fe5266_1    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libstdcxx-ng              9.3.0               hd4cf53a_17  
libtiff                   4.3.0                hf544144_1    conda-forge
libwebp-base              1.2.0                h7f98852_2    conda-forge
libzopfli                 1.0.3                h9c3ff4c_0    conda-forge
llvmlite                  0.37.0                   pypi_0    pypi
locket                    0.2.0                      py_2    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
matplotlib-base           3.4.2            py37hdd32ed1_0    conda-forge
msgpack                   1.0.3                    pypi_0    pypi
msgpack-numpy             0.4.7.1                  pypi_0    pypi
ncurses                   6.3                  h7f8727e_2  
networkx                  2.6.3              pyhd8ed1ab_1    conda-forge
numba                     0.54.1                   pypi_0    pypi
numpy                     1.19.0           py37h8960a57_0    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
opencv-python             4.2.0.34                 pypi_0    pypi
openjpeg                  2.4.0                hb52868f_1    conda-forge
openssl                   1.1.1k               h7f98852_0    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandas                    1.3.1            py37h219a48f_0    conda-forge
partd                     1.2.0              pyhd8ed1ab_0    conda-forge
pillow                    8.3.1            py37h0f21c89_0    conda-forge
pip                       21.2.2           py37h06a4308_0  
pooch                     1.5.2              pyhd8ed1ab_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyfakewebcam              0.1.0                    pypi_0    pypi
pyopenssl                 21.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.6              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1            py37h89c1867_4    conda-forge
python                    3.7.11               h12debd9_0  
python-blosc              1.7.0           py37hf484d3e_1001    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.7                     2_cp37m    conda-forge
pytz                      2021.3             pyhd8ed1ab_0    conda-forge
pywavelets                1.1.1            py37h902c9e0_3    conda-forge
pyyaml                    5.3.1                    pypi_0    pypi
pyzmq                     20.0.0                   pypi_0    pypi
readline                  8.1                  h27cfd23_0  
requests                  2.25.1                   pypi_0    pypi
scikit-image              0.18.2           py37h219a48f_0    conda-forge
scipy                     1.7.0            py37h29e03ee_1    conda-forge
setuptools                58.0.4           py37h06a4308_0  
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.1.8                he1b5a44_3    conda-forge
sqlite                    3.36.0               hc218d9a_0  
tifffile                  2021.7.2           pyhd8ed1ab_0    conda-forge
tk                        8.6.11               h1ccaba5_0  
toolz                     0.11.2             pyhd8ed1ab_0    conda-forge
torch                     1.10.0                   pypi_0    pypi
tornado                   6.1              py37h5e8e339_1    conda-forge
tqdm                      4.62.3                   pypi_0    pypi
typing-extensions         4.0.0                    pypi_0    pypi
urllib3                   1.26.7             pyhd8ed1ab_0    conda-forge
wheel                     0.37.0             pyhd3eb1b0_1  
xz                        5.2.5                h7b6447c_0  
yaml                      0.2.5                h516909a_0    conda-forge
zfp                       0.5.5                h9c3ff4c_5    conda-forge
zlib                      1.2.11               h7b6447c_3  
zstd                      1.5.0                ha95c52a_0    conda-forge
```

echo $PYTHONPATH
(empty)

echo $PATH
/home/pm/miniconda3/envs/avatarify/bin:/home/pm/miniconda3/condabin:/home/pm/.local/bin:/home/pm/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin

**Logs**

**Comment by j2l** [comment]
https://github.com/alievk/avatarify-python/issues/411 fixes it
