### ISSUE TITLE
ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by sldk123123** [alievk/avatarify-python#445]
Traceback (most recent call last):
  File "afy/cam_fomm.py", line 6, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by JohanAR** [comment]
Did you follow each step of the "install" and "run" sections in the manual?

**Comment by Rakenz** [comment]
> Did you follow each step of the "install" and "run" sections in the manual?

Hi bro
How can i contact you

**Comment by JohanAR** [comment]
I'm sorry, I'm just a volunteer co-maintainer of this github project, I don't have time to provide support to help people get it running. Alievk made avatarify-python as an experiment and then decided to open up its source code so that other developers could learn from it, it was never meant to be user friendly. If you can't get it running using the provided documentation, maybe [Avatarify mobile](http://avatarify.ai) is more suited for you.

**Comment by Realrichard57** [comment]
> Traceback (most recent call last):
> File "afy/cam_fomm.py", line 6, in
> import requests
> ModuleNotFoundError: No module named 'requests'

were you able to find a solution to this?

**Comment by Kingso42** [comment]
> Traceback (most recent call last):
> File "afy/cam_fomm.py", line 6, in 
> import requests
> ModuleNotFoundError: No module named 'requests'

Please who’s able to find solution to the.  I’m having same issue

**Comment by Jblaac7** [comment]
@Kingso42 I'm having the same issues. Please have you been able to come up with a solution yet?

**Comment by Kingso42** [comment]
> @Kingso42 I'm having the same issues. Please have you been able to come up with a solution yet?

No. I still can’t.  Have you fixed yours ?

**Comment by Jblaac7** [comment]
@Kingso42 Not yet. But still trying

**Comment by Kingso42** [comment]
> @Kingso42 Not yet. But still trying 

okay

**Comment by Kingso42** [comment]
> @Kingso42 Not yet. But still trying

I had this error, so I reran a clean install and then I had the yaml module not found error
I ran these commands
pip install pyyaml
pip install requests
pip install cv2
pip install scipy
pip install face_alignment
pip install sklearn
pip install pandas
I also copied the 7 files from the modules folder into the fomm folder.

This now works

**Comment by Jblaac7** [comment]
@Kingso42 oh wow! I thought the issue was from my laptop so I sent it back to the person I got it from to have it changed. Can you please message me on WhatsApp with this number? ‪+1 (210) 465‑3722‬   I'm gonna try it again once I get the new laptop and if it works or I need your assistance again I will text you on WhatsApp.

**Comment by Spykey231** [comment]
> Traceback (most recent call last):
> File "afy/cam_fomm.py", line 6, in 
> import requests
> ModuleNotFoundError: No module named 'requests'

Same issue

**Comment by Testedxxzz** [comment]
> 

I tried this but the cv2 isn't working

**Comment by Utehfo00** [comment]
Useless, no one helping just scammers. Wasted 2 weeks with this

**Comment by jcemos57** [comment]
> > @Kingso42 Not yet. But still trying
> 
> I had this error, so I reran a clean install and then I had the yaml module not found error I ran these commands pip install pyyaml pip install requests pip install cv2 pip install scipy pip install face_alignment pip install sklearn pip install pandas I also copied the 7 files from the modules folder into the fomm folder.
> 
> This now works

how do i locate module folder and the fomm folder?

**Comment by blast-cloud** [comment]
> Useless, no one helping just scammers. Wasted 2 weeks with this

Lol, I know it can be frustrating… I tried running this for a week and nothing, … then i  finally i got it working on my Linux machine.

**Comment by JohanAR** [comment]
@blast-cloud if you have the time and energy, pull requests to fix the install scripts and or instructions are welcome :)

**Comment by MICKYGEM** [comment]
Pip install pyyaml 
pip install requests
pip install numpy
Conda install opencv 
Pip install pyyaml 
Pip install zmq
Pip install msgpack 
Pip install msgpack_numpy

For any other help 
What's app

‪+234 811 513 3627‬

**Comment by MICKYGEM** [comment]
pip install pyyaml 
pip install numpy 
Conda install opencv 
Pip install pyyaml 
Pip install zmq 
Pip install msgpack 
Pip install msgpack_numpy

Contact for any other help

**Comment by Morten202** [comment]
Please anyone can help bc i have been battling with this for the past 3 days. It didn't open the camera at the module
(base) C:\Users\matek\avatarify-python>run_windows.bat
Traceback (most recent call last):
File "afy/cam_fomm.py", line 6, in
import requests
ModuleNotFoundError: No module named 'requests'

(avatarify) C:\Users\matek\avatarify-python>

**Comment by SanPatrick01** [comment]
call pip install -r requirements.txt

**Comment by Morten202** [comment]
Please who can help me to install it?

**Comment by Morten202** [comment]
> call pip install -r requirements.txt

(base) C:\Users\matek>call pip install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

(base) C:\Users\matek>
