### ISSUE TITLE
how can i run this without Nvidia graphics card 

### ISSUE THREAD

**Issue by jackefrain01** [alievk/avatarify-python#456]
i keep getting this message +++++++

C:\Users\USER\deepfake\envs\avatarify\lib\site-packages\torch\cuda\__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  ..\c10\cuda\CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 100
Traceback (most recent call last):
  File "afy/cam_fomm.py", line 218, in <module>
    **predictor_args
  File "C:\Users\USER\avatarify\afy\predictor_local.py", line 48, in __init__
    self.generator, self.kp_detector = self.load_checkpoints()
  File "C:\Users\USER\avatarify\afy\predictor_local.py", line 66, in load_checkpoints
    checkpoint = torch.load(self.checkpoint_path, map_location=self.device)
  File "C:\Users\USER\deepfake\envs\avatarify\lib\site-packages\torch\serialization.py", line 581, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "C:\Users\USER\deepfake\envs\avatarify\lib\site-packages\torch\serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\Users\USER\deepfake\envs\avatarify\lib\site-packages\torch\serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'vox-adv-cpk.pth.tar'

how can i resolve this please

**Comment by jackefrain01** [comment]
@JohanAR

**Comment by JohanAR** [comment]
A good start would be to read the text that you just gave me :)

> FileNotFoundError: [Errno 2] No such file or directory: 'vox-adv-cpk.pth.tar'

**Comment by jackefrain01** [comment]
> A good start would be to read the text that you just gave me :)
> 
> > FileNotFoundError: [Errno 2] No such file or directory: 'vox-adv-cpk.pth.tar'

how can resolve this?  i have been trying

**Comment by JohanAR** [comment]
Read the documentation again, it is explained there.

**Comment by davidlorex** [comment]
> 
> i keep getting this message +++++++
> 
> C:\Users\USER\deepfake\envs\avatarify\lib\site-packages\torch\cuda\__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  ..\c10\cuda\CUDAFunctions.cpp:100.)
>   return torch._C._cuda_getDeviceCount() > 100
> Traceback (most recent call last):
>   File "afy/cam_fomm.py", line 218, in <module>
>     **predictor_args
>   File "C:\Users\USER\avatarify\afy\predictor_local.py", line 48, in __init__
>     self.generator, self.kp_detector = self.load_checkpoints()
>   File "C:\Users\USER\avatarify\afy\predictor_local.py", line 66, in load_checkpoints
>     checkpoint = torch.load(self.checkpoint_path, map_location=self.device)
>   File "C:\Users\USER\deepfake\envs\avatarify\lib\site-packages\torch\serialization.py", line 581, in load
>     with _open_file_like(f, 'rb') as opened_file:
>   File "C:\Users\USER\deepfake\envs\avatarify\lib\site-packages\torch\serialization.py", line 230, in _open_file_like
>     return _open_file(name_or_buffer, mode)
>   File "C:\Users\USER\deepfake\envs\avatarify\lib\site-packages\torch\serialization.py", line 211, in __init__
>     super(_open_file, self).__init__(open(name, mode))
> FileNotFoundError: [Errno 2] No such file or directory: 'vox-adv-cpk.pth.tar'
> 
> 
> 
> how can i resolve this please

From the error message. It shows your system is not NVIDIA  compatible. You should consider getting  a geming system with gtx or NVIDIA.  Else you can run it on google colab .

**Comment by JohanAR** [comment]
@davidlorex that is not the error message. The error is "FileNotFoundError: [Errno 2] No such file or directory: 'vox-adv-cpk.pth.tar'" as I've said earlier.

The text you're referring to is a warning. While I haven't tested it myself, it should be possible to run Avatarify using the CPU. It will be extremely slow, but it should not crash on startup because of this.

**Comment by Jerriecruiz** [comment]
Can i use avatarify in mac?

**Comment by JohanAR** [comment]
@Jerriecruiz  If you don't read the documentation, the answer is: No, you can't use avatarify :) It does not matter if you have Mac, Linux or Windows. Being able to read and follow instructions is the number 1 preconditions to using this software.

**Comment by Yvngthills** [comment]
Please send me a text on my WhatsApp number on +16319316913

**Comment by davidlorex** [comment]
> Can i use avatarify in mac?

Yes.  Use colab

**Comment by vicmore101** [comment]
I am really confused here, Can some advice on how to run Avatarify on my Mac system.

**Comment by johnsonomar01** [comment]
g

> I am really confused here, Can some advice on how to run Avatarify on my Mac system.

google collab but i cant even change my pictures to local pics

**Comment by badmuspro** [comment]
Please can I run avatarify on Window 11 ??

**Comment by nuelljune** [comment]
> Please can I run avatarify on Window 11 ??

Did you get an answer for this? I've tried and tried, but it's not working, I don't know if it's because I'm on Win11

**Comment by badmuspro** [comment]
> > Please can I run avatarify on Window 11 ??
> 
> Did you get an answer for this? I've tried and tried, but it's not working, I don't know if it's because I'm on Win11

It’s working I gave it a try and did it successfully on Win 11….

**Comment by preciouskel** [comment]
How do I run avatarify on Google colab. Someone please help

**Comment by Chopalone** [comment]
> g
> 
> 
> 
> > I am really confused here, Can some advice on how to run Avatarify on my Mac system.
> 
> 
> 
> google collab but i cant even change my pictures to local pics

How did you go about it please?

**Comment by johnsonomar01** [comment]
On Wed, Apr 26, 2023 at 4:58 AM Chopalone ***@***.***> wrote:

> g
>
> I am really confused here, Can some advice on how to run Avatarify on my
> Mac system.
>
> google collab but i cant even change my pictures to local pics
>
> How did you go about it please?
>

I eventually got it but now I’m stock in using camtwist. I’ve given up

**Comment by davidlorex** [comment]
> How do I run avatarify on Google colab. Someone please help

Have you visit the Colab server with your Gmail signed in, if you still do not get the process .watch the avatarify colab video on YouTube that's should help. Let me know if that helps .

**Comment by davidlorex** [comment]
> 

Are you trying to get it done for your macbook or windows. Let me know so I know exactly how to help

**Comment by johnsonomar01** [comment]
On MacBook

**Comment by davidlorex** [comment]
> 
> i keep getting this message +++++++
> 
> C:\Users\USER\deepfake\envs\avatarify\lib\site-packages\torch\cuda\__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  ..\c10\cuda\CUDAFunctions.cpp:100.)
>   return torch._C._cuda_getDeviceCount() > 100
> Traceback (most recent call last):
>   File "afy/cam_fomm.py", line 218, in <module>
>     **predictor_args
>   File "C:\Users\USER\avatarify\afy\predictor_local.py", line 48, in __init__
>     self.generator, self.kp_detector = self.load_checkpoints()
>   File "C:\Users\USER\avatarify\afy\predictor_local.py", line 66, in load_checkpoints
>     checkpoint = torch.load(self.checkpoint_path, map_location=self.device)
>   File "C:\Users\USER\deepfake\envs\avatarify\lib\site-packages\torch\serialization.py", line 581, in load
>     with _open_file_like(f, 'rb') as opened_file:
>   File "C:\Users\USER\deepfake\envs\avatarify\lib\site-packages\torch\serialization.py", line 230, in _open_file_like
>     return _open_file(name_or_buffer, mode)
>   File "C:\Users\USER\deepfake\envs\avatarify\lib\site-packages\torch\serialization.py", line 211, in __init__
>     super(_open_file, self).__init__(open(name, mode))
> FileNotFoundError: [Errno 2] No such file or directory: 'vox-adv-cpk.pth.tar'
> 
> 
> 
> how can i resolve this please

Error 2: No such file or directory 'vox-adv-cpk.pth.tar

With my broad experience,  I can tell from this that you have not put in the VOX zip file in the avatarify-python  path.
