### ISSUE TITLE
issues on trying to install on mac

### ISSUE THREAD

**Issue by codexx23** [alievk/avatarify-python#476]
**Describe the bug**
 really need some assistance on how to install for mac

**To Reproduce**

**Info (please complete the following information):**
 - OS (e.g., Linux): 
 - GPU model: 

 - Any other relevant information: 

**Screenshots**

**Logs**

**Comment by JohanAR** [comment]
I assume you tried following the install instructions. Where and how did it fail? You really need to provide logs to show what you've done and what happened if you want anyone to be able to help you. System information is useful too.

**Comment by codexx23** [comment]
ii installed git, anaconda{miniconda} then i downloaded and unpack the repository which is the **avatarify python** folder exactly that says on the installation page. then i imputed the codes firstly directory not found. then i finally sorted that the tried imputing  '' bash scripts/install_mac.sh'' and ENTER.  i started seeing errors why?? i am using :  **MacOS high sierra**   and   processor  **2.4ghz intel core 2 duo.**  and i feel a **video explanation** will be very useful. or explaining in **full detail** step by step  '**JohanAR**'  thanks.

**Comment by JohanAR** [comment]
>  i started seeing errors why?? 

How could anyone possibly know _why_ you are getting errors if we don't even know what those errors were? You need to copy the contents of the terminal window, i.e. both the commands that you wrote and the output from the programs. Some people take a photo of their screen and upload that, but that is not ok :) I might still not be able to help you, because I've never used a Mac, but perhaps some other user can be able to answer. And I mean that you should copy the text. 

There are no detailed guide because avatarify-python was not made for end users. This was more of an experiment that Alievk made for fun, and then decided to share here on github. Then volunteer contributors, such as myself, added more features, and I think Mac support was one of those contributions made by users. I.e. there is no guarantee that any experienced Mac users are even reading these issues.

And unlike an app on the app store, there is no-one who gains anything by people using this, so there is no real incentive for anyone to try to make it more user-friendly for beginners. You're expected to have some computer knowledge so you can troubleshoot any issues you run in to, and then preferably contribute fixes to the project if you solve any problems. People might answer your questions if they can, but don't have too high hopes of anyone guiding you through getting it up and running.

If following the existing install instructions doesn't work, there's a risk that some Python/Conda stuff needs to be updated in the source code. So it's possible that there's no quick and easy answer to why it isn't working for you, and that some volunteer needs to spend time fixing it.

**Comment by russ-russ0** [comment]
Tried google colab and this was my error

Last login: Fri Feb 10 15:30:29 on ttys000
(base) macbookpro@Macbook-MacBook-Pro ~ % cd avatarify-python
(base) macbookpro@Macbook-MacBook-Pro avatarify-python % ./run_mac.sh --is-client --in-addr tcp://4.tcp.ngrok.io:13038 --out-addr tcp://8.tcp.ngrok.io:17405
[1676032417.685883] Loading Predictor
[1676032417.847887] Receiving from tcp://8.tcp.ngrok.io:17405
[1676032419.572709] Trying camera with id 0
[1676032421.082542] Trying camera with id 1
[1676032423.157168] Could not read from camera with id 1
[1676032423.169242] Trying camera with id 2
OpenCV: out device of bound (0-1): 2
OpenCV: camera failed to properly initialize!
[1676032423.169813] Camera with id 2 is not available
[1676032423.169857] Trying camera with id 3
OpenCV: out device of bound (0-1): 3
OpenCV: camera failed to properly initialize!
[1676032423.170030] Camera with id 3 is not available
[1676032423.170180] Selected camera 0
Traceback (most recent call last):
  File "afy/cam_fomm.py", line 227, in <module>
    cap.start()
  File "/Users/macbookpro/avatarify-python/afy/videocaptureasync.py", line 44, in start
    raise RuntimeError(f"Failed to succesfully grab frame from the camera (timeout={WARMUP_TIMEOUT}s). Try to restart.")
RuntimeError: Failed to succesfully grab frame from the camera (timeout=10.0s). Try to restart.

**Comment by ichyTao** [comment]
> Tried google colab and this was my error
> 
> Last login: Fri Feb 10 15:30:29 on ttys000 (base) macbookpro@Macbook-MacBook-Pro ~ % cd avatarify-python (base) macbookpro@Macbook-MacBook-Pro avatarify-python % ./run_mac.sh --is-client --in-addr tcp://4.tcp.ngrok.io:13038 --out-addr tcp://8.tcp.ngrok.io:17405 [1676032417.685883] Loading Predictor [1676032417.847887] Receiving from tcp://8.tcp.ngrok.io:17405 [1676032419.572709] Trying camera with id 0 [1676032421.082542] Trying camera with id 1 [1676032423.157168] Could not read from camera with id 1 [1676032423.169242] Trying camera with id 2 OpenCV: out device of bound (0-1): 2 OpenCV: camera failed to properly initialize! [1676032423.169813] Camera with id 2 is not available [1676032423.169857] Trying camera with id 3 OpenCV: out device of bound (0-1): 3 OpenCV: camera failed to properly initialize! [1676032423.170030] Camera with id 3 is not available [1676032423.170180] Selected camera 0 Traceback (most recent call last): File "afy/cam_fomm.py", line 227, in cap.start() File "/Users/macbookpro/avatarify-python/afy/videocaptureasync.py", line 44, in start raise RuntimeError(f"Failed to succesfully grab frame from the camera (timeout={WARMUP_TIMEOUT}s). Try to restart.") RuntimeError: Failed to succesfully grab frame from the camera (timeout=10.0s). Try to restart.

I'm having the same bug on M2 MacBook Pro, How did you possible solve yours? I'll need your assistance to solve mine as well, Your help will be much appreciated.

**Comment by David001123** [comment]
> Tried google colab and this was my error
> 
> Last login: Fri Feb 10 15:30:29 on ttys000 (base) macbookpro@Macbook-MacBook-Pro ~ % cd avatarify-python (base) macbookpro@Macbook-MacBook-Pro avatarify-python % ./run_mac.sh --is-client --in-addr tcp://4.tcp.ngrok.io:13038 --out-addr tcp://8.tcp.ngrok.io:17405 [1676032417.685883] Loading Predictor [1676032417.847887] Receiving from tcp://8.tcp.ngrok.io:17405 [1676032419.572709] Trying camera with id 0 [1676032421.082542] Trying camera with id 1 [1676032423.157168] Could not read from camera with id 1 [1676032423.169242] Trying camera with id 2 OpenCV: out device of bound (0-1): 2 OpenCV: camera failed to properly initialize! [1676032423.169813] Camera with id 2 is not available [1676032423.169857] Trying camera with id 3 OpenCV: out device of bound (0-1): 3 OpenCV: camera failed to properly initialize! [1676032423.170030] Camera with id 3 is not available [1676032423.170180] Selected camera 0 Traceback (most recent call last): File "afy/cam_fomm.py", line 227, in cap.start() File "/Users/macbookpro/avatarify-python/afy/videocaptureasync.py", line 44, in start raise RuntimeError(f"Failed to succesfully grab frame from the camera (timeout={WARMUP_TIMEOUT}s). Try to restart.") RuntimeError: Failed to succesfully grab frame from the camera (timeout=10.0s). Try to restart.

Please I would love to know how you solved this issues, my predictor is not loading, only have the 2 sector. Not loading just said loading predictor…
