### ISSUE TITLE
 'vox-adv-cpk.pth.tar'

### ISSUE THREAD

**Issue by Kingempirefx** [alievk/avatarify-python#479]
Hello I have downloaded the vox-adv-cpk.pth.tar and put it in my avatarify folder but the prompt says it cant be found. (Added Screenshot and the prompt output) command: run_windows.bat (replaced my name with "...") [1610296410.702018] Loading Predictor C:\Users\...\avatarify\afy\predictor_local.py:34: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details. config = yaml.load(f) Traceback (most recent call last): File "afy/cam_fomm.py", line 214, in <module> **predictor_args File "C:\Users\...\avatarify\afy\predictor_local.py", line 26, in __init__ self.generator, self.kp_detector = self.load_checkpoints()
![7adfb40a-c1ee-4056-aad1-15dd865f7b09](https://user-images.githubusercontent.com/119724311/205548077-a653f080-4ad7-4a6c-b5ee-bcb2a4c4b38f.jpg)
 File "C:\Users\...\avatarify\afy\predictor_local.py", l
![7adfb40a-c1ee-4056-aad1-15dd865f7b09](https://user-images.githubusercontent.com/119724311/205548141-bf37821a-fbd5-4ecf-a20b-3f9c1e3391cb.jpg)
![7adfb40a-c1ee-4056-aad1-15dd865f7b09](https://user-images.githubusercontent.com/119724311/205548874-ec8902e0-af83-4a98-a397-5b5e82f2b56f.jpg)
ine 44, in load_checkpoints checkpoint = torch.load(self.checkpoint_path, map_location=self.device) File "C:\Users\...\miniconda3\envs\avatarify\lib\site-packages\torch\serialization.py", line 365, in load f = open(f, 'rb') FileNotFoundError: [Errno 2] No such file or directory: 'vox-adv-cpk.pth.tar' Here the Screenshot of my Folder:

**Comment by JohanAR** [comment]
The file manager photos show a different directory than the one you have open in the terminal. Write ls (short for "list") in the powershell terminal to list the files in that directory.

Also it's easier to read issue reports if you copy the text from the terminal to here, and mark the text as code (The <> icon in the github text editor)

**Comment by Kingempirefx** [comment]
ok thanks
