### ISSUE TITLE
RTX 4080 supported???

### ISSUE THREAD

**Issue by twerpyfie** [alievk/avatarify-python#485]
**Describe the bug**
Finally i got it to start. But then when i align my face and press x, the programm crashes and i get an error.

**Info (please complete the following information):**
- OS:
 Windows
 - GPU model: 
NVIDIA GeForce RTX 4080

 - Any other relevant information: 
Dont know if Pytorch, Cuda 11.7 & the 4080 are compatible...

```conda info

     active environment : avatarify
    active env location : C:\Users\Fynn\miniconda3\envs\avatarify
            shell level : 2
       user config file : C:\Users\Fynn\.condarc
 populated config files :
          conda version : 22.11.1
    conda-build version : 3.23.3
         python version : 3.7.13.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=12.0=0
                          __win=0=0
       base environment : C:\Users\Fynn\miniconda3  (writable)
      conda av data dir : C:\Users\Fynn\miniconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\Fynn\miniconda3\pkgs
                          C:\Users\Fynn\.conda\pkgs
                          C:\Users\Fynn\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\Fynn\miniconda3\envs
                          C:\Users\Fynn\.conda\envs
                          C:\Users\Fynn\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/22.11.1 requests/2.28.1 CPython/3.7.13 Windows/10 Windows/10.0.19041
          administrator : False
             netrc file : None
           offline mode : False```
```conda list
# packages in environment at C:\Users\Fynn\miniconda3\envs\avatarify:
#
# Name                    Version                   Build  Channel
blas                      1.0                         mkl
blosc                     1.21.3               hdccc3a2_0    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
c-blosc2                  2.6.1                h183a6f4_0    conda-forge
ca-certificates           2022.4.26            haa95532_0    anaconda
certifi                   2022.12.7                pypi_0    pypi
cfitsio                   4.0.0                hd67004f_0    conda-forge
charls                    2.3.4                h39d44d4_0    conda-forge
charset-normalizer        2.1.1                    pypi_0    pypi
cloudpickle               2.2.0              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6                    pypi_0    pypi
cudatoolkit               11.0.221             h74a9793_0
cytoolz                   0.12.0           py37hcc03f2d_0    conda-forge
dask-core                 2022.2.0           pyhd8ed1ab_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
face-alignment            1.3.5                    pypi_0    pypi
flit-core                 3.6.0              pyhd3eb1b0_0
freetype                  2.12.1               h546665d_1    conda-forge
fsspec                    2022.11.0          pyhd8ed1ab_0    conda-forge
giflib                    5.2.1                h8d14728_2    conda-forge
git                       2.34.1               haa95532_0    anaconda
idna                      3.4                      pypi_0    pypi
imagecodecs               2021.11.20       py37hfea8715_2    conda-forge
imageio                   2.22.4             pyhfa7a67d_1    conda-forge
importlib-metadata        5.1.0                    pypi_0    pypi
intel-openmp              2022.2.1         h57928b3_19741    conda-forge
jpeg                      9e                   h8ffe710_2    conda-forge
jxrlib                    1.1                  h8ffe710_2    conda-forge
krb5                      1.20.1               heb0366b_0    conda-forge
lcms2                     2.14                 h90d422f_0    conda-forge
lerc                      3.0                  h0e60522_0    conda-forge
libaec                    1.0.6                h39d44d4_0    conda-forge
libblas                   3.9.0              16_win64_mkl    conda-forge
libbrotlicommon           1.0.9                hcfcfb64_8    conda-forge
libbrotlidec              1.0.9                hcfcfb64_8    conda-forge
libbrotlienc              1.0.9                hcfcfb64_8    conda-forge
libcblas                  3.9.0              16_win64_mkl    conda-forge
libcurl                   7.86.0               h68f0423_2    conda-forge
libdeflate                1.10                 h8ffe710_0    conda-forge
libhwloc                  2.8.0                h039e092_1    conda-forge
libiconv                  1.17                 h8ffe710_0    conda-forge
liblapack                 3.9.0              16_win64_mkl    conda-forge
libpng                    1.6.39               h19919ed_0    conda-forge
libsqlite                 3.40.0               hcfcfb64_0    conda-forge
libssh2                   1.10.0               h9a1e1f7_3    conda-forge
libtiff                   4.4.0                hc4061b1_0    conda-forge
libuv                     1.40.0               he774522_0
libwebp-base              1.2.4                h8ffe710_0    conda-forge
libxcb                    1.13              hcd874cb_1004    conda-forge
libxml2                   2.10.3               hc3477c8_0    conda-forge
libzlib                   1.2.13               hcfcfb64_4    conda-forge
libzopfli                 1.0.3                h0e60522_0    conda-forge
llvmlite                  0.39.1                   pypi_0    pypi
locket                    1.0.0              pyhd8ed1ab_0    conda-forge
lz4-c                     1.9.3                h8ffe710_1    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
mkl                       2022.1.0           h6a75c08_874    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
networkx                  2.5                        py_0    conda-forge
ninja                     1.10.2               haa95532_5
ninja-base                1.10.2               h6d14046_5
numba                     0.56.4                   pypi_0    pypi
numpy                     1.19.0           py37hae9e721_0    conda-forge
opencv-python             4.6.0.66                 pypi_0    pypi
openjpeg                  2.5.0                hc9384bd_1    conda-forge
openssl                   3.0.7                hcfcfb64_1    conda-forge
packaging                 22.0               pyhd8ed1ab_0    conda-forge
partd                     1.3.0              pyhd8ed1ab_0    conda-forge
pillow                    9.2.0            py37h42a8222_2    conda-forge
pip                       22.3.1             pyhd8ed1ab_0    conda-forge
pthread-stubs             0.4               hcd874cb_1001    conda-forge
pthreads-win32            2.9.1                hfa6e2cd_3    conda-forge
python                    3.7.12          h900ac77_100_cpython    conda-forge
python-blosc              1.7.0           py37h6538335_1001    conda-forge
python_abi                3.7                     3_cp37m    conda-forge
pytorch                   1.7.1           py3.7_cuda110_cudnn8_0    pytorch
pywavelets                1.3.0            py37hec80d1f_0    conda-forge
pyyaml                    6.0              py37hcc03f2d_4    conda-forge
requests                  2.28.1                   pypi_0    pypi
scikit-image              0.19.2           py37h9386db6_0    conda-forge
scipy                     1.7.3            py37hb6553fb_0    conda-forge
setuptools                65.5.1             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyhd3eb1b0_1
snappy                    1.1.9                hfb803bf_2    conda-forge
sqlite                    3.40.0               hcfcfb64_0    conda-forge
tbb                       2021.7.0             h91493d7_1    conda-forge
tifffile                  2021.11.2          pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h8ffe710_0    conda-forge
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
torchvision               0.2.2                      py_3    pytorch
tqdm                      4.64.1                   pypi_0    pypi
typing_extensions         4.4.0            py37haa95532_0
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
urllib3                   1.26.13                  pypi_0    pypi
vc                        14.3                 h3d8a991_9    conda-forge
vs2015_runtime            14.32.31332          h1d6e394_9    conda-forge
wheel                     0.38.4             pyhd8ed1ab_0    conda-forge
xorg-libxau               1.0.9                hcd874cb_0    conda-forge
xorg-libxdmcp             1.1.3                hcd874cb_0    conda-forge
xz                        5.2.6                h8d14728_0    conda-forge
yaml                      0.2.5                h8ffe710_2    conda-forge
zfp                       0.5.5                h0e60522_8    conda-forge
zipp                      3.11.0                   pypi_0    pypi
zlib-ng                   2.0.6                h8ffe710_0    conda-forge
zstd                      1.5.2                h7755175_4    conda-forge```
:: Environment info
```set | findstr /I "CUDA CONDA Python" | findstr /V "Path"
CONDA_DEFAULT_ENV=avatarify
CONDA_EXE=C:\Users\Fynn\miniconda3\condabin\..\Scripts\conda.exe
CONDA_EXES="C:\Users\Fynn\miniconda3\condabin\..\Scripts\conda.exe"
CONDA_PREFIX=C:\Users\Fynn\miniconda3\envs\avatarify
CONDA_PREFIX_1=C:\Users\Fynn\miniconda3
CONDA_PROMPT_MODIFIER=(avatarify)
CONDA_PYTHON_EXE=C:\Users\Fynn\miniconda3\python.exe
CONDA_SHLVL=2
CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7
CUDA_PATH_V11_7=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7```
```echo %PATH:;=&echo.%
C:\Users\Fynn\miniconda3\envs\avatarify
C:\Users\Fynn\miniconda3\envs\avatarify\Library\mingw-w64\bin
C:\Users\Fynn\miniconda3\envs\avatarify\Library\usr\bin
C:\Users\Fynn\miniconda3\envs\avatarify\Library\bin
C:\Users\Fynn\miniconda3\envs\avatarify\Scripts
C:\Users\Fynn\miniconda3\envs\avatarify\bin
C:\Users\Fynn\miniconda3\condabin
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\bin
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\libnvvp
.
C:\ProgramData\Oracle\Java\javapath
C:\Program Files\Common Files\Oracle\Java\javapath
C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler
C:\Windows\system32
C:\Windows
C:\Windows\System32\Wbem
C:\Windows\System32\WindowsPowerShell\v1.0
C:\Windows\System32\OpenSSH
C:\Users\Fynn\AppData\Local\Microsoft\WindowsApps
C:\adb
C:\WINDOWS\system32
C:\WINDOWS
C:\WINDOWS\System32\Wbem
C:\WINDOWS\System32\WindowsPowerShell\v1.0
C:\WINDOWS\System32\OpenSSH
C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit
C:\Program Files\dotnet
C:\Program Files (x86)\dotnet
C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR
C:\Program Files\Git\cmd
C:\Program Files\NVIDIA Corporation\Nsight Compute 2022.2.0
C:\Users\Fynn\AppData\Local\Programs\Python\Python311\Scripts
C:\Users\Fynn\AppData\Local\Programs\Python\Python311
C:\Program Files\platform-tools
C:\Users\Fynn\AppData\Local\Microsoft\WindowsApps
C:\Users\Fynn\.dotnet\tools
C:\Users\Fynn\AppData\Local\Microsoft\WindowsApps
C:\Users\Fynn\.dotnet\tools```

-->



**Logs**
```Traceback (most recent call last):
  File "afy/cam_fomm.py", line 316, in <module>
    out = predictor.predict(frame)
  File "C:\Users\Fynn\avatarify\afy\predictor_local.py", line 104, in predict
    use_relative_jacobian=self.relative, adapt_movement_scale=self.adapt_movement_scale)
  File "C:\Users\Fynn\avatarify\afy\predictor_local.py", line 28, in normalize_kp
    jacobian_diff = torch.matmul(kp_driving['jacobian'], torch.inverse(kp_driving_initial['jacobian']))
RuntimeError: CUDA error: operation not supported when calling `cusparseCreate(handle)````

**Comment by geekedpriest** [comment]
@twerpyfie are you on WhatsApp or something I can contact you with ? ![image](https://user-images.githubusercontent.com/120290986/208160676-12eea097-7b48-4ed6-9c98-c159aa98ea17.jpeg) I'm stuck here .

**Comment by IsaacDarko** [comment]
having the same issue as this, can you help me?

**Comment by Nene020** [comment]
Telegram  @King_Gabos
