### ISSUE TITLE
Please I need help on this while using colab errors

### ISSUE THREAD

**Issue by stteg01** [alievk/avatarify-python#506]
[1674090889.305879] Loading Predictor
Traceback (most recent call last):
  File "afy/cam_fomm.py", line 205, in <module>
    from afy import predictor_remote
  File "C:\Users\core i5\avatarify-python\afy\predictor_remote.py", line 2, in <module>
    from networking import SerializingContext, check_connection
  File "C:\Users\core i5\avatarify-python\afy\networking.py", line 1, in <module>
    import zmq
ModuleNotFoundError: No module named 'zmq'

**Comment by Vazkido** [comment]
i get the same error too

**Comment by Vazkido** [comment]
> [1674090889.305879] Loading Predictor Traceback (most recent call last): File "afy/cam_fomm.py", line 205, in from afy import predictor_remote File "C:\Users\core i5\avatarify-python\afy\predictor_remote.py", line 2, in from networking import SerializingContext, check_connection File "C:\Users\core i5\avatarify-python\afy\networking.py", line 1, in import zmq ModuleNotFoundError: No module named 'zmq'





i am having exactly same error, can someone please tell me how to fix this?? tunnel is opened and working fine, then why this error??

**Comment by Vazkido** [comment]
> [1674090889.305879] Loading Predictor Traceback (most recent call last): File "afy/cam_fomm.py", line 205, in from afy import predictor_remote File "C:\Users\core i5\avatarify-python\afy\predictor_remote.py", line 2, in from networking import SerializingContext, check_connection File "C:\Users\core i5\avatarify-python\afy\networking.py", line 1, in import zmq ModuleNotFoundError: No module named 'zmq'

pip install zmq



use that code and it solved the problem

**Comment by warmfart** [comment]
I mean the oath in the terminal

**Comment by George152-max** [comment]
DM wa.me/+2348119663355
To fix this issue

**Comment by Vazkido** [comment]
> I mean the path in the terminal 

What exactly is the error you're getting?

**Comment by Vazkido** [comment]
> DM https://wa.me/+2348119663355
> 
> To fix this issue 

I can fix any issue in both Mac and Windows..
You Dm

**Comment by MICKYGEM** [comment]
Pip install request
Pip install numpy 
Conda install opencv
pip install zmq
Pip install msgpack 
Pip install msgpack_numoy

**Comment by yzhu319** [comment]
Run this command
`conda install -c conda-forge numpy PyYAML requests msgpack-numpy pyzmq opencv`
