### ISSUE TITLE
> > > > Mine works now. I followed the message someone sent me;

### ISSUE THREAD

**Issue by XpliDGhost** [alievk/avatarify-python#523]
> > > > Mine works now. I followed the message someone sent me;
> > > > I had this error, so I reran a clean install and then I had the yaml module not found error I ran these commands
> > > > pip install pyyaml pip install requests pip install cv2 pip install scipy pip install face_alignment pip install sklearn pip install pandas
> > > > I also copied the 7 files from the modules folder into the fomm folder. This now works
> > > 
> > > 
> > > @Jblaac7 please if you can help just do a simple tutorial on this it’ll help a lot thanks 🙏🏽
> > 
> > 
> > Bro just run those command in the miniconda thats all
> 
> Pip install CV2 doesn’t work

Now run the bat file it should work now

are you talking about running this now: run_windows.bat

_Originally posted by @ayamga1 in https://github.com/alievk/avatarify-python/issues/484#issuecomment-1358389986_

**Comment by Jblaac7** [comment]
@XpliDGhost Yes run the last comment after everything run_windows.bat

**Comment by favouriteQ** [comment]
please help me how to the fake video call using avatarify and obs studio on my Intel(R) Core(TM) i3-10110U CPU @ 2.10GHz   2.59 GHz please 

teach me how this is my whatsapp number 08020779924 thank you

**Comment by Peterwills65** [comment]
> 

i can help

**Comment by kingsley456** [comment]
Please I need help to mine stop at solving environment

**Comment by Emmanueleze996** [comment]
hi @XpliDGhost how did you copied the 7 files from the modules folder into the fomm folder. please direct me

**Comment by lewis30adams** [comment]
CondaVerificationError: The package for mkl located at C:\Users\HELLO\miniconda3\pkgs\mkl-2022.1.0-h6a75c08_874
appears to be corrupted. The path 'Library/bin/mkl_vml_cmpt.2.dll'
specified in the package manifest cannot be found.

CondaVerificationError: The package for mkl located at C:\Users\HELLO\miniconda3\pkgs\mkl-2022.1.0-h6a75c08_874
appears to be corrupted. The path 'Library/bin/mkl_vml_def.2.dll'
specified in the package manifest cannot be found.

CondaVerificationError: The package for mkl located at C:\Users\HELLO\miniconda3\pkgs\mkl-2022.1.0-h6a75c08_874
appears to be corrupted. The path 'Library/bin/mkl_vml_mc.2.dll'
specified in the package manifest cannot be found.

CondaVerificationError: The package for mkl located at C:\Users\HELLO\miniconda3\pkgs\mkl-2022.1.0-h6a75c08_874
appears to be corrupted. The path 'Library/bin/mkl_vml_mc2.2.dll'
specified in the package manifest cannot be found.

CondaVerificationError: The package for mkl located at C:\Users\HELLO\miniconda3\pkgs\mkl-2022.1.0-h6a75c08_874
appears to be corrupted. The path 'Library/bin/mkl_vml_mc3.2.dll'
specified in the package manifest cannot be found.

SafetyError: The package for libblas located at C:\Users\HELLO\miniconda3\pkgs\libblas-3.9.0-16_win64_mkl
appears to be corrupted. The path 'Library/bin/libblas.dll'
has an incorrect size.
  reported size: 25820688 bytes
  actual size: 4440064 bytes

**Comment by lewis30adams** [comment]
please what this meant to show ?

**Comment by justme220011** [comment]
\miniconda3\envs\avatarify\lib\site-packages\torch\functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\TensorShape.cpp:3191.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Traceback (most recent call last):
  File "afy/cam_fomm.py", line 218, in <module>
    **predictor_args
  File "C:\Users\OMEN\avatarify-python-youtube\afy\predictor_local.py", line 49, in __init__
    self.fa = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D, flip_input=True, device=self.device)
  File "C:\Users\OMEN\miniconda3\envs\avatarify\lib\enum.py", line 354, in __getattr__
    raise AttributeError(name) from None
AttributeError: _2D

please i need help on this one
