### ISSUE TITLE
Avatarify

### ISSUE THREAD

**Issue by Alvinjulong1424** [alievk/avatarify-python#525]
Please I need help : [ERROR:0] global /Users/travis/build/skvark/opencv-python/opencv/modules/videoio/src/cap.cpp (193) open VIDEOIO(AVFOUNDATION): raised unknown C++ exception!

Traceback (most recent call last):
  File "afy/cam_fomm.py", line 226, in <module>
    cap = VideoCaptureAsync(cam_id)
  File "/Users/user/avatarify-python/afy/videocaptureasync.py", line 17, in __init__
    raise RuntimeError("Cannot open camera")
RuntimeError: Cannot open camera

**Comment by JohanAR** [comment]
Sounds like your camera is not supported by OpenCV. Try using a different webcam.

**Comment by MICKYGEM** [comment]
Dm WhatsApp for beta instruction

‪+234 811 513 3627‬
