### ISSUE TITLE
My windows.bat not running... Solution

### ISSUE THREAD

**Issue by Noniboy1000** [alievk/avatarify-python#537]
base) C:\Users\USER\avatarify-python>run-windows.bat
'run-windows.bat' is not recognized as an internal or external command,
operable program or batch file.

(base) C:\Users\USER\avatarify-python>run_windows.bat
Traceback (most recent call last):
  File "C:\Users\USER\miniconda3\lib\site-packages\numpy\core\__init__.py", line 22, in <module>
    from . import multiarray
  File "C:\Users\USER\miniconda3\lib\site-packages\numpy\core\multiarray.py", line 12, in <module>
    from . import overrides
  File "C:\Users\USER\miniconda3\lib\site-packages\numpy\core\overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "afy/cam_fomm.py", line 8, in <module>
    import numpy as np
  File "C:\Users\USER\miniconda3\lib\site-packages\numpy\__init__.py", line 150, in <module>
    from . import core
  File "C:\Users\USER\miniconda3\lib\site-packages\numpy\core\__init__.py", line 48, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.7 from "C:\Users\USER\miniconda3\envs\avatarify\python.exe"
  * The NumPy version is: "1.21.6"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: DLL load failed: The specified module could not be found.

**Comment by ostronic** [comment]
> base) C:\Users\USER\avatarify-python>run-windows.bat 'run-windows.bat' is not recognized as an internal or external command, operable program or batch file.
> 
> (base) C:\Users\USER\avatarify-python>run_windows.bat Traceback (most recent call last): File "C:\Users\USER\miniconda3\lib\site-packages\numpy\core__init__.py", line 22, in from . import multiarray File "C:\Users\USER\miniconda3\lib\site-packages\numpy\core\multiarray.py", line 12, in from . import overrides File "C:\Users\USER\miniconda3\lib\site-packages\numpy\core\overrides.py", line 7, in from numpy.core._multiarray_umath import ( ImportError: DLL load failed: The specified module could not be found.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "afy/cam_fomm.py", line 8, in import numpy as np File "C:\Users\USER\miniconda3\lib\site-packages\numpy__init__.py", line 150, in from . import core File "C:\Users\USER\miniconda3\lib\site-packages\numpy\core__init__.py", line 48, in raise ImportError(msg) ImportError:
> 
> IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
> 
> Importing the numpy C-extensions failed. This error can happen for many reasons, often due to issues with your setup or how NumPy was installed.
> 
> We have compiled some common reasons and troubleshooting tips at:
> 
> ```
> https://numpy.org/devdocs/user/troubleshooting-importerror.html
> ```
> 
> Please note and check the following:
> 
> * The Python version is: Python3.7 from "C:\Users\USER\miniconda3\envs\avatarify\python.exe"
> * The NumPy version is: "1.21.6"
> 
> and make sure that they are the versions you expect. Please carefully study the documentation linked above for further help.
> 
> Original error was: DLL load failed: The specified module could not be found.

I AM AVAILABLE TO HELP ANYONE HAVING ISSUES INSTALLING AVATARIFY ON WINDOWS PC.
HMU ON TELEGRAM @Qxchan
Please go straight to the point ‼️
