### ISSUE TITLE
Cant open it

### ISSUE THREAD

**Issue by malaksyan64** [alievk/avatarify-python#548]
./run.sh: line 84: conda: command not found
./run.sh: line 84: /etc/profile.d/conda.sh: No such file or directory
./run.sh: line 85: conda: command not found
[1679700584.063654] Loading Predictor
Traceback (most recent call last):
  File "/home/spiros/avatarify-python/afy/cam_fomm.py", line 193, in <module>
    from afy import predictor_local
  File "/home/spiros/avatarify-python/afy/predictor_local.py", line 4, in <module>
    from modules.keypoint_detector import KPDetector
ModuleNotFoundError: No module named 'modules.keypoint_detector'; 'modules' is not a package

**Comment by JohanAR** [comment]
Looks like you're not following the instructions in the manual.
