### ISSUE TITLE
Issue running run_windows.bat on my Conda

### ISSUE THREAD

**Issue by Tqq23** [alievk/avatarify-python#555]
![image](https://user-images.githubusercontent.com/103373782/229293651-47d2ba84-69cf-4d56-a096-13d574a1bb4a.png)
 
what should I do when this happens,

**Comment by JohanAR** [comment]
Did you follow all the steps of the installation instructions first?

**Comment by Tqq23** [comment]
Yes, @JohanAR I did follow all steps in the video which was provided

**Comment by JohanAR** [comment]
@Tqq23 what video? The only installation instructions for avatarify-python that I know of are in the written documentation.

**Comment by Tqq23** [comment]
And then use the google colaboratory which then gave me this error
[1680524711.261392] Loading Predictor
Traceback (most recent call last):
  File "afy/cam_fomm.py", line 205, in <module>
    from afy import predictor_remote
  File "C:\Users\emman\avatarify-python\afy\predictor_remote.py", line 2, in <module>
    from networking import SerializingContext, check_connection
  File "C:\Users\emman\avatarify-python\afy\networking.py", line 1, in <module>
    import zmq
ModuleNotFoundError: No module named 'zmq'

**Comment by workingnike** [comment]
Traceback (most recent call last):
  File "afy/cam_fomm.py", line 6, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by JohanAR** [comment]
> @JohanAR https://youtu.be/lym9ANVb120 this video tutorial

Didn't know alievk had made one, but check the installation section of the manual instead, the video might be out of date.

**Comment by edgebtc2** [comment]
i have solve the problem view here https://prnt.sc/JUo0hY9QFFx0
send a text on WhatsApp +13233072096 ill connect with you on anydesk and have it fixed. https://prnt.sc/JUo0hY9QFFx0

**Comment by MICKYGEM** [comment]
> ![image](https://user-images.githubusercontent.com/103373782/229293651-47d2ba84-69cf-4d56-a096-13d574a1bb4a.png)
> 
>  
> 
> what should I do when this happens, 

You can send a direct message to me on WhatsApp let’s fix ‘em all
‪+2348115133627‬

Teamviewer is welcomed
