### ISSUE TITLE
laptop does not have internal cam  and external cam refused to work

### ISSUE THREAD

**Issue by azukeytic** [alievk/avatarify-python#566]
C:\Users\ROG\avatarify-python>run_windows.bat
[1681708587.395264] Loading Predictor
C:\Users\ROG\miniconda3\envs\avatarify\lib\site-packages\torch\functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\TensorShape.cpp:3191.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
[1681708590.842747] Trying camera with id 0
[ WARN:0] global C:\projects\opencv-python\opencv\modules\videoio\src\cap_msmf.cpp (674) SourceReaderCB::~SourceReaderCB terminating async callback
Traceback (most recent call last):
  File "afy/cam_fomm.py", line 221, in <module>
    cam_id = select_camera(config)
  File "afy/cam_fomm.py", line 166, in select_camera
    cam_frames = cam_selector.query_cameras(config['query_n_cams'])
  File "C:\Users\ROG\avatarify-python\afy\camera_selector.py", line 16, in query_cameras
    cap = cv2.VideoCapture(camid)
KeyboardInterrupt
Terminate batch job (Y/N)?

**Comment by azukeytic** [comment]
anyone have solution to the above

**Comment by JohanAR** [comment]
Sounds like your camera might not be supported by OpenCV, which avatarify uses. You could try using a different camera.

**Comment by Shawnkafuma** [comment]
Please I'm also kinda facing the same issues my webcam is not detecting my face.its totally blank and I have granted permission but all in vein.. anyone to help me

**Comment by azukeytic** [comment]
Kindly delete yhmal
