### ISSUE TITLE
Cant Run windows.bat

### ISSUE THREAD

**Issue by larryblaqi** [alievk/avatarify-python#588]
(avatarify) D:\avatarify-python>run_windows.bat
Traceback (most recent call last):
File "afy/cam_fomm.py", line 4, in
import yaml
ModuleNotFoundError: No module named 'yaml'

(avatarify) D:\avatarify-python>

i cant get mine running. do you have an idea whats wrong

**Comment by JohanAR** [comment]
It's difficult for anyone to try to help you with that little information. The new issue template is there because you're supposed to answer those questions, not delete it. Also I'm pretty sure I've seen other issues about "no module named yaml", have you looked for suggestions in any of those?

**Comment by larryblaqi** [comment]
Ive checked all i could find and still no result
"geforce GTX 1060
6gb graphics card
16gb ram"


(avatarify) C:\Users\RAZER\Avatarify\avatarify-python>run_windows.bat
[1684266604.562087] Loading Predictor
Traceback (most recent call last):
  File "afy/cam_fomm.py", line 216, in <module>
    from afy import predictor_local
  File "C:\Users\RAZER\Avatarify\avatarify-python\afy\predictor_local.py", line 8, in <module>
    import face_alignment
  File "C:\Users\RAZER\AppData\Roaming\Python\Python37\site-packages\face_alignment\__init__.py", line 7, in <module>
    from .api import FaceAlignment, LandmarksType, NetworkSize
  File "C:\Users\RAZER\AppData\Roaming\Python\Python37\site-packages\face_alignment\api.py", line 4, in <module>
    from skimage import io
  File "C:\Users\RAZER\AppData\Roaming\Python\Python37\site-packages\skimage\_shared\lazy.py", line 62, in __getattr__
    return importlib.import_module(f'{package_name}.{name}')
  File "C:\ProgramData\miniconda3\envs\avatarify\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\RAZER\AppData\Roaming\Python\Python37\site-packages\skimage\io\__init__.py", line 7, in <module>
    from .manage_plugins import *
  File "C:\Users\RAZER\AppData\Roaming\Python\Python37\site-packages\skimage\io\manage_plugins.py", line 23, in <module>
    from .collection import imread_collection_wrapper
  File "C:\Users\RAZER\AppData\Roaming\Python\Python37\site-packages\skimage\io\collection.py", line 12, in <module>
    from PIL import Image, __version__ as pil_version
  File "C:\ProgramData\miniconda3\envs\avatarify\lib\site-packages\PIL\Image.py", line 100, in <module>
    from . import _imaging as core
ImportError: DLL load failed: The specified module could not be found.

**Comment by JohanAR** [comment]
Did you get any errors when running the install script?

**Comment by larryblaqi** [comment]
yes

**Comment by larryblaqi** [comment]
This was after installing all the dependencies that was recommended on this topic

**Comment by ostronic** [comment]
I AM AVAILABLE TO HELP ANYONE HAVING ISSUES INSTALLING AVATARIFY ON WINDOWS PC.
HMU ON TELEGRAM @Qxchan
Please ho straight to the point ‼️

**Comment by MICKYGEM** [comment]
Dm WhatsApp for beta instruction

‪+234 811 513 3627‬
