### ISSUE TITLE
Error on run_windows.bat miniconda

### ISSUE THREAD

**Issue by GhostShot3** [alievk/avatarify-python#589]
Error:
![1](https://github.com/alievk/avatarify-python/assets/18537420/6c3dfca3-3224-4b85-b4e7-42b710363a83)

**To Reproduce**
I do all this [steps](https://github.com/alievk/avatarify-python/tree/master/docs#windows-1)+this steps on this https://github.com/alievk/avatarify-python/issues/572 issue and when i finaly do `run_windows.bat` command on Miniconda promt

 - OS: Windows 10 Pro
 - GPU model: RTX 3070

`conda info`
![1](https://github.com/alievk/avatarify-python/assets/18537420/1a0fdde1-107b-4871-a31d-46dac28494b1)

`conda list`
![2](https://github.com/alievk/avatarify-python/assets/18537420/04a3faa6-24ff-4f7c-9f07-feeb067a74cd)

How i do it?!
echo $PYTHONPATH
echo $PATH

**Comment by JohanAR** [comment]
I've never used conda, but I would guess you do something like this to install the missing dependency:

```
conda activate avatarify
conda install -y numpy==1.19.0
```

**Comment by ostronic** [comment]
I AM AVAILABLE TO HELP ANYONE HAVING ISSUES INSTALLING AVATARIFY ON WINDOWS PC.
HMU ON TELEGRAM @Qxchan
Please ho straight to the point ‼️

**Comment by GhostShot3** [comment]
> I've never used conda, but I would guess you do something like this to install the missing dependency:
> 
> ```
> conda activate avatarify
> conda install -y numpy==1.19.0
> ```

![666678](https://github.com/alievk/avatarify-python/assets/18537420/8b680533-068b-46b4-b549-4102c877fab2)

**Comment by ostronic** [comment]
I AM AVAILABLE TO HELP ANYONE HAVING ISSUES INSTALLING AVATARIFY ON WINDOWS PC.
HMU ON TELEGRAM @Qxchan
Please go straight to the point ‼️

**Comment by MICKYGEM** [comment]
> missing

Dm no char... 

So I could take you on the proper installation tho if you don't mind . 
What's app

‪+234 811 513 3627‬

**Comment by komilaria** [comment]
i have the same an issue please give me instruction 
why it happened in this step

**Comment by wizzytech16** [comment]
here is the error i got while trying to run_windows.bat
please anyone can help?



(avatarify) C:\Users\gmont\Documents\Avatarify\avatarify-python>run_windows.bat
Traceback (most recent call last):
  File "afy/cam_fomm.py", line 6, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

(avatarify) C:\Users\gmont\Documents\Avatarify\avatarify-python>

**Comment by ostronic** [comment]
> i have the same an issue please give me instruction why it happened in this step

Hit me up for all your IT Solutions on mail @ :[ zagzag.drank337@passinbox.com](url) ,  or checkout my website:[]( https://shorturl.at/H2T9Y)

**Comment by ostronic** [comment]
> here is the error i got while trying to run_windows.bat please anyone can help?
> 
> (avatarify) C:\Users\gmont\Documents\Avatarify\avatarify-python>run_windows.bat Traceback (most recent call last): File "afy/cam_fomm.py", line 6, in import requests ModuleNotFoundError: No module named 'requests'
> 
> (avatarify) C:\Users\gmont\Documents\Avatarify\avatarify-python>

Hit me up for all your IT Solutions on mail @ : zagzag.drank337@passinbox.com , or checkout my website: https://shorturl.at/H2T9Y (DM to resolve the issue)
