### ISSUE TITLE
Avatarify error when i install i get this error messages

### ISSUE THREAD

**Issue by sagabra** [alievk/avatarify-python#594]
Your installed version is: 0

Note that strict channel priority may have removed packages required for satisfiability.

The system cannot find the file specified.
Cloning into 'fomm'...
remote: Enumerating objects: 211, done.
remote: Total 211 (delta 0), reused 0 (delta 0), pack-reused 211Receiving objects:  81% (171/211), 57.10 MiB | 2.57 MiB/Receiving objects: 100% (211/211), 58.16 MiB | 1.90 MiB/s, done.

Resolving deltas: 100% (108/108), done.

Usage:
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

option --use-feature: invalid choice: '2020-resolver' (choose from 'fast-deps', 'truststore', 'no-binary-enable-wheel-cache')

(avatarify) C:\Users\User\avatarify-python-youtube>run_windows.bat
Traceback (most recent call last):
  File "afy/cam_fomm.py", line 6, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by ostronic** [comment]
I AM AVAILABLE TO HELP ANYONE HAVING ISSUES INSTALLING AVATARIFY ON WINDOWS PC.
HMU ON TELEGRAM @Qxchan
Please go straight to the point ‼️

**Comment by ostronic** [comment]
> Your installed version is: 0
> 
> Note that strict channel priority may have removed packages required for satisfiability.
> 
> The system cannot find the file specified. Cloning into 'fomm'... remote: Enumerating objects: 211, done. remote: Total 211 (delta 0), reused 0 (delta 0), pack-reused 211Receiving objects: 81% (171/211), 57.10 MiB | 2.57 MiB/Receiving objects: 100% (211/211), 58.16 MiB | 1.90 MiB/s, done.
> 
> Resolving deltas: 100% (108/108), done.
> 
> Usage: pip install [options] [package-index-options] ... pip install [options] -r [package-index-options] ... pip install [options] [-e] ... pip install [options] [-e] ... pip install [options] <archive url/path> ...
> 
> option --use-feature: invalid choice: '2020-resolver' (choose from 'fast-deps', 'truststore', 'no-binary-enable-wheel-cache')
> 
> (avatarify) C:\Users\User\avatarify-python-youtube>run_windows.bat Traceback (most recent call last): File "afy/cam_fomm.py", line 6, in import requests ModuleNotFoundError: No module named 'requests'

I AM AVAILABLE TO HELP ANYONE HAVING ISSUES INSTALLING AVATARIFY ON WINDOWS PC.
HMU ON TELEGRAM @Qxchan
Please go straight to the point ‼️

**Comment by MICKYGEM** [comment]
> Your installed version is: 0
> 
> 
> 
> Note that strict channel priority may have removed packages required for satisfiability.
> 
> 
> 
> The system cannot find the file specified.
> 
> Cloning into 'fomm'...
> 
> remote: Enumerating objects: 211, done.
> 
> remote: Total 211 (delta 0), reused 0 (delta 0), pack-reused 211Receiving objects:  81% (171/211), 57.10 MiB | 2.57 MiB/Receiving objects: 100% (211/211), 58.16 MiB | 1.90 MiB/s, done.
> 
> 
> 
> Resolving deltas: 100% (108/108), done.
> 
> 
> 
> Usage:
> 
>   pip install [options] <requirement specifier> [package-index-options] ...
> 
>   pip install [options] -r <requirements file> [package-index-options] ...
> 
>   pip install [options] [-e] <vcs project url> ...
> 
>   pip install [options] [-e] <local project path> ...
> 
>   pip install [options] <archive url/path> ...
> 
> 
> 
> option --use-feature: invalid choice: '2020-resolver' (choose from 'fast-deps', 'truststore', 'no-binary-enable-wheel-cache')
> 
> 
> 
> (avatarify) C:\Users\User\avatarify-python-youtube>run_windows.bat
> 
> Traceback (most recent call last):
> 
>   File "afy/cam_fomm.py", line 6, in <module>
> 
>     import requests
> 
> ModuleNotFoundError: No module named 'requests'


No char...  

Dm WhatsApp for beta instruction

‪+234 811 513 3627‬
