### ISSUE TITLE
I ran into a cuda runtime error after installing the avatarify on rtx 40 series

### ISSUE THREAD

**Issue by SanPatrick01** [alievk/avatarify-python#633]
**Describe the bug**

**To Reproduce**

**Info (please complete the following information):**
 - OS (e.g., Linux): 
 - GPU model: 

 - Any other relevant information: 

**Screenshots**

**Logs**

**Comment by SanPatrick01** [comment]
![image](https://github.com/alievk/avatarify-python/assets/94569954/5a990c23-d872-4433-b82d-03093c231cc3)


Here is what it looks like 🙏🙏🙏🥲

**Comment by concept3ee** [comment]
write me on whatsapp 07038512363

**Comment by mindmy111** [comment]
INVIDIA RTX 4070 , WINDOWS 11 , DRIVER TYPE DCH
have already install drivers update and have also installed cuda

Traceback (most recent call last):
File "afy/cam_fomm.py", line 316, in
out = predictor.predict(frame)
File "C:\Users\babli\avatarify\afy\predictor_local.py", line 102, in predict
kp_norm = normalize_kp(kp_source=self.kp_source, kp_driving=kp_driving,
File "C:\Users\babli\avatarify\afy\predictor_local.py", line 28, in normalize_kp
jacobian_diff = torch.matmul(kp_driving['jacobian'], torch.inverse(kp_driving_initial['jacobian']))
RuntimeError: CUDA error: operation not supported when calling cusparseCreate(handle)

any help to fix RuntimeError: CUDA error: operation not supported when calling

**Comment by IsaacDarko** [comment]
facing the same issue, can someone please help?

**Comment by SanPatrick01** [comment]
> facing the same issue, can someone please help?
> 
> 

Send dm to WhatsApp 

‪+234 811 513 3627‬
