### ISSUE TITLE
Avatarify is not working

### ISSUE THREAD

**Issue by Talkvibes** [alievk/avatarify-python#641]
(avatarify) C:\Users\oluwa\avatarify-python>run_windows.bat
[1691226719.616641] Loading Predictor
Traceback (most recent call last):
  File "afy/cam_fomm.py", line 216, in <module>
    from afy import predictor_local
  File "C:\Users\oluwa\avatarify-python\afy\predictor_local.py", line 8, in <module>
    import face_alignment
  File "C:\ProgramData\miniconda3\envs\avatarify\lib\site-packages\face_alignment\__init__.py", line 7, in <module>
    from .api import FaceAlignment, LandmarksType, NetworkSize
  File "C:\ProgramData\miniconda3\envs\avatarify\lib\site-packages\face_alignment\api.py", line 4, in <module>
    from skimage import io
  File "C:\ProgramData\miniconda3\envs\avatarify\lib\site-packages\skimage\_shared\lazy.py", line 62, in __getattr__
    return importlib.import_module(f'{package_name}.{name}')
  File "C:\ProgramData\miniconda3\envs\avatarify\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\ProgramData\miniconda3\envs\avatarify\lib\site-packages\skimage\io\__init__.py", line 7, in <module>
    from .manage_plugins import *
  File "C:\ProgramData\miniconda3\envs\avatarify\lib\site-packages\skimage\io\manage_plugins.py", line 23, in <module>
    from .collection import imread_collection_wrapper
  File "C:\ProgramData\miniconda3\envs\avatarify\lib\site-packages\skimage\io\collection.py", line 12, in <module>
    from PIL import Image, __version__ as pil_version
  File "C:\ProgramData\miniconda3\envs\avatarify\lib\site-packages\PIL\Image.py", line 100, in <module>
    from . import _imaging as core
ImportError: DLL load failed: The specified module could not be found.

**Comment by SanPatrick01** [comment]
Use 
Pip install pillow==9.0.0


You can also contact me on WhatsApp too

https://wa.me/message/Q2R3YYTP46XKG1

**Comment by okieszion** [comment]
No need using code or pips, 20minutes u should be done with installations... You can contact us if you need assistance.
 https://wa.link/mcvi63
