### ISSUE TITLE
Server side error

### ISSUE THREAD

**Issue by aqk-93** [alievk/avatarify-python#655]
warnings.warn("The default behavior for interpolate/upsample with float scale_factor changed "
Process Process-1:
Traceback (most recent call last):
  File "/root/miniconda3/envs/avatarify/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/root/miniconda3/envs/avatarify/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/avatarify/afy/predictor_worker.py", line 76, in recv_worker
    msg = socket.recv_data()
  File "/avatarify/afy/networking.py", line 122, in recv_data
    md = self.recv_json(flags=flags)  # metadata text
  File "/root/miniconda3/envs/avatarify/lib/python3.7/site-packages/zmq/sugar/socket.py", line 765, in recv_json
    return self._deserialize(msg, lambda buf: jsonapi.loads(buf, **kwargs))
  File "/root/miniconda3/envs/avatarify/lib/python3.7/site-packages/zmq/sugar/socket.py", line 590, in _deserialize
    return load(recvd)
  File "/root/miniconda3/envs/avatarify/lib/python3.7/site-packages/zmq/sugar/socket.py", line 765, in <lambda>
    return self._deserialize(msg, lambda buf: jsonapi.loads(buf, **kwargs))
  File "/root/miniconda3/envs/avatarify/lib/python3.7/site-packages/zmq/utils/jsonapi.py", line 54, in loads
    s = s.decode('utf8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9e in position 0: invalid start byte

**Comment by SanPatrick01** [comment]
What error is this ?

**Comment by SanPatrick01** [comment]
Check my video on YouTube

**Comment by aqk-93** [comment]
The issue that I am understanding is that the client sends 2 messages for each frame. One message is a JSON containing metadata and the other message is a frame tensor. So, all odd-numbered messages should be JSONs and even-numbered messages should be frames. The server, upon receiving the first message, parses it as JSON and the second message as a frame. However, if a message is not sent for some reason, the ordering gets disrupted. The message that is parsed as JSON is actually a frame, leading to this error.
