### ISSUE TITLE
Colab loading predictor 

### ISSUE THREAD

**Issue by Edwin2476** [alievk/avatarify-python#668]
my colab avatarify keeps loading predictor as pasting my copied run_window.bat 
please help me solve this

**Comment by SanPatrick01** [comment]
Will drop a video soon 
Or join my community...

**Comment by ryce139** [comment]
Would your video include solving this error?

"EnvironmentNameNotFound: Could not find conda environment: avatarify
You can list all discoverable environments with `conda info --envs`.


Traceback (most recent call last):
  File "C:\Users\GLORIA DAN ORAWARI\avatarify-python\afy\cam_fomm.py", line 4, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml''

**Comment by HP0014** [comment]
the avartars are not deleting despite confirming it has been deleted, and when i try to upload file it says it is disabled. boss i need you to put me through on that

**Comment by SanPatrick01** [comment]
Till you see the video sir

**Comment by ryce139** [comment]
watched the video but keep getting this error any fix?

(avatarify) C:\Users\hp\avatarify-python>call git clone https://github.com/alievk/first-order... fomm
Cloning into 'fomm'...
remote: Repository not found.
fatal: repository 'https://github.com/alievk/first-order.../' not found

**Comment by HP0014** [comment]
what are you talking about boss, i need you to be specific!

**Comment by ryce139** [comment]
so watched the video and did ever every but stuck here

(avatarify) C:\Users\hp\avatarify-python>run_windows.bat --is-client --in-addr tcp://2.tcp.eu.ngrok.io:19184 --out-addr tcp://0.tcp.eu.ngrok.io:12650
[1696710960.175058] Loading Predictor
[1696710961.564162] Receiving from tcp://0.tcp.eu.ngrok.io:12650

**Comment by HP0014** [comment]
what your community handle boss

**Comment by SanPatrick01** [comment]
Colab Avatarify installation on CPU laptops
https://youtu.be/gfPs3tiXYOk

**Comment by davidlorex** [comment]
> my colab avatarify keeps loading predictor as pasting my copied run_window.bat 
> please help me solve this


A diffrent colab https://youtu.be/wOGMdQ1IK1c watch video

**Comment by davidlorex** [comment]
> Would your video include solving this error?
> 
> "EnvironmentNameNotFound: Could not find conda environment: avatarify
> You can list all discoverable environments with `conda info --envs`.
> 
> 
> Traceback (most recent call last):
>   File "C:\Users\hp\avatarify-python\afy\cam_fomm.py", line 4, in <module>
>     import yaml
> ModuleNotFoundError: No module named 'yaml''


Diffrent colab watch video https://youtu.be/wOGMdQ1IK1c

**Comment by davidlorex** [comment]
Watch  video for colab use https://youtu.be/wOGMdQ1IK1c newly lunched

**Comment by Elektrobotcdp** [comment]
> my colab avatarify keeps loading predictor as pasting my copied run_window.bat please help me solve this


**message @Qxchan on Telegram . for any issues.**

**Comment by Updatedme** [comment]
https://youtu.be/UnDCMPKywY8

**Comment by Updatedme** [comment]
https://youtu.be/UnDCMPKywY8?feature=shared
I have illustrated the easy step by step process in my youtube video.
You can do it yourself for contact me for further assistance

Contact: https://wa.me/message/GXQYWX4XRTXGB1

**Comment by Dennisogbe** [comment]
> so watched the video and did ever every but stuck here
> 
> (avatarify) C:\Users\hp\avatarify-python>run_windows.bat --is-client --in-addr tcp://2.tcp.eu.ngrok.io:19184 --out-addr tcp://0.tcp.eu.ngrok.io:12650 [1696710960.175058] Loading Predictor [1696710961.564162] Receiving from tcp://0.tcp.eu.ngrok.io:12650

on how to fix this proble DM me on dis number 08032823595

**Comment by Updatedme** [comment]
Contact: https://wa.me/message/GXQYWX4XRTXGB1
