### ISSUE TITLE
ModuleNotfounderror 

### ISSUE THREAD

**Issue by Supremod1** [alievk/avatarify-python#690]
After running *run_windows.bat*
I get this results , can someone help me out .

(avatarify) C:\Users\Supremo\avatarify-python>run_windows.bat
Traceback (most recent call last):
  File "afy/cam_fomm.py", line 6, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by SanPatrick01** [comment]
call pip install -r requirements.txt

**Comment by Mohammedsagito** [comment]
am having same issues
please help me out

**Comment by SanPatrick01** [comment]
What type of error ... can you send to WhatsApp 
Will share the link on YouTube here too : ‪+234 811 513 3627‬

Avatarify easy installation
https://youtu.be/nW5_-zPVmec

**Comment by Updatedme** [comment]
If you have any problem with avatarify . Contact me for solutions 100% results. You can also watch my installation video that shows you how to do it yourself. Or simply ask for help from my whatsapp contact 
https://wa.me/message/GXQYWX4XRTXGB1

**Comment by Updatedme** [comment]
> am having same issues
> please help me out

If you have any problem with avatarify . Contact me for solutions 100% results. You can also watch my installation video that shows you how to do it yourself. Or simply ask for help from my whatsapp contact 
https://wa.me/message/GXQYWX4XRTXGB1

**Comment by Updatedme** [comment]
> After running *run_windows.bat*
> I get this results , can someone help me out .
> 
> (avatarify) C:\Users\Supremo\avatarify-python>run_windows.bat
> Traceback (most recent call last):
>   File "afy/cam_fomm.py", line 6, in <module>
>     import requests
> ModuleNotFoundError: No module named 'requests'
> 

If you have any problem with avatarify . Contact me for solutions 100% results. You can also watch my installation video that shows you how to do it yourself. Or simply ask for help from my whatsapp contact 
https://wa.me/message/GXQYWX4XRTXGB1
