### ISSUE TITLE
Solution to all avatarify problem

### ISSUE THREAD

**Issue by Updatedme** [alievk/avatarify-python#693]
<  If you have any problem with avatarify . Contact me for solutions 100% results. You can also watch my installation video that shows you how to do it yourself. Or simply ask for help from my whatsapp contact 
https://wa.me/message/GXQYWX4XRTXGB1 >

**Comment by Updatedme** [comment]
If you have any problem with avatarify . Contact me for solutions 100% results. You can also watch my installation video that shows you how to do it yourself. Or simply ask for help from my whatsapp contact 
https://wa.me/message/GXQYWX4XRTXGB1

**Comment by Updatedme** [comment]
If you have any problem with avatarify . Contact me for solutions 100% results on apple macbook and any windows.
You can also watch my installation video that shows you how to do it yourself. Or simply ask for help from my whatsapp contact 
https://wa.me/message/GXQYWX4XRTXGB1
+2347081306010

**Comment by ozborn404** [comment]
if you have problem installing avatarify contact me i was able to gather all the new required version  for it to install properly.
whatsapp:2347044156622

**Comment by Updatedme** [comment]
If you have any problem with avatarify . Contact me for solutions 100% results on apple macbook and any windows.
You can also watch my installation video that shows you how to do it yourself. Or simply ask for help from my whatsapp contact
https://wa.me/message/GXQYWX4XRTXGB1
+2347081306010

**Comment by Updatedme** [comment]
If you have any problem with avatarify . Contact me for solutions 100% results on apple macbook and any windows.
You can also watch my installation video that shows you how to do it yourself. Or simply ask for help from my whatsapp contact
https://wa.me/message/GXQYWX4XRTXGB1
+2347081306010

**Comment by Supremod1** [comment]
After running run_windows.bat
This is the results i get can someone please help me out 
(avatarify) C:\Users\Supremo\avatarify>run_windows.bat
[1704765602.903649] Loading Predictor
Traceback (most recent call last):
  File "afy/cam_fomm.py", line 218, in <module>
    **predictor_args
  File "C:\Users\Supremo\avatarify\afy\predictor_local.py", line 49, in __init__
    self.fa = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D, flip_input=True, device=self.device)
  File "C:\Users\Supremo\miniconda3\envs\avatarify\lib\enum.py", line 354, in __getattr__
    raise AttributeError(name) from None
AttributeError: _2D

**Comment by SanPatrick01** [comment]
Change the 2D to TWOD

**Comment by Supremod1** [comment]
> Change the 2D to TWOD

Please how can I change the 2D to TWOD

**Comment by SanPatrick01** [comment]
Check the directory on the error 
Or download anydesk and send the link to me

**Comment by Supremod1** [comment]
> Check the directory on the error Or download anydesk and send the link to me

Oh wow , thank you in advance. Please do have telegram or WhatsApp so that we can chat there . I have anydesk and teamviewer .

**Comment by PopeFR** [comment]
Please I need help my avatarify keeps saying windows bat... Is not recognized as an internal or external command , operable program or batch file  same thing if I try git clone https:// github..... Please how do I start and finish it's been giving me problems since I started it .

**Comment by PopeFR** [comment]
@Updatedme 
Please I asked a question previously please help me

**Comment by Updatedme** [comment]
> Please I need help my avatarify keeps saying windows bat... Is not recognized as an internal or external command , operable program or batch file  same thing if I try git clone https:// github..... Please how do I start and finish it's been giving me problems since I started it .

What's the configuration and spec of you computer.  

https://wa.me/message/GXQYWX4XRTXGB1
 Contact me here for promt reply

**Comment by Updatedme** [comment]
> @Updatedme 
> Please I asked a question previously please help me 

I got your message on my whatsapp . I replied . 
It belive that has been resolved.  

YOU ARE WELCOME 😊

**Comment by Updatedme** [comment]
If you have any problem with avatarify . Contact me for solutions 100% results on apple macbook and any windows.
You can also watch my installation video that shows you how to do it yourself. Or simply ask for help from my whatsapp contact
https://wa.me/message/GXQYWX4XRTXGB1
+2347081306010

**Comment by gfame** [comment]
print('Copy-paste to the terminal the command below and run (press Enter)\n')print('Mac:')print(f'./run_mac.sh --is-client --in-addr {in_addr} --out-addr {out_addr}')print('\nWindows:')print(f'run_windows.bat --is-client --in-addr {in_addr} --out-addr {out_addr}')print('\nLinux:')print(f'./run.sh --is-client --in-addr {in_addr} --out-addr {out_addr}')

 
Next steps:

**Comment by gfame** [comment]
print('Copy-paste to the terminal the command below and run (press Enter)\n')
print('Mac:')
print(f'./run_mac.sh --is-client --in-addr {in_addr} --out-addr {out_addr}')
print('\nWindows:')
print(f'run_windows.bat --is-client --in-addr {in_addr} --out-addr {out_addr}')
print('\nLinux:')
print(f'./run.sh --is-client --in-addr {in_addr} --out-addr {out_addr}')

Copy-paste to the terminal the command below and run (press Enter)

Mac:
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
[<ipython-input-19-4a78138efeff>](https://ubuhu5ao3wo-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab_20240212-060142_RC00_606195215#) in <cell line: 3>()
      1 print('Copy-paste to the terminal the command below and run (press Enter)\n')
      2 print('Mac:')
----> 3 print(f'./run_mac.sh --is-client --in-addr {in_addr} --out-addr {out_addr}')
      4 print('\nWindows:')
      5 print(f'run_windows.bat --is-client --in-addr {in_addr} --out-addr {out_addr}')

NameError: name 'in_addr' is not defined

please how do I solve this, I have been stuck here

**Comment by Urchman7102** [comment]
If you need any help on avatarify related issues contact me on Whatsapp+2349036407102

**Comment by 12ayfa** [comment]
> After running run_windows.bat This is the results i get can someone please help me out (avatarify) C:\Users\Supremo\avatarify>run_windows.bat [1704765602.903649] Loading Predictor Traceback (most recent call last): File "afy/cam_fomm.py", line 218, in **predictor_args File "C:\Users\Supremo\avatarify\afy\predictor_local.py", line 49, in **init** self.fa = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D, flip_input=True, device=self.device) File "C:\Users\Supremo\miniconda3\envs\avatarify\lib\enum.py", line 354, in **getattr** raise AttributeError(name) from None AttributeError: _2D

How did you get it fixed??
