### ISSUE TITLE
Keep getting a cuda related error

### ISSUE THREAD

**Issue by giantbaobab** [alievk/avatarify-python#696]
keep getting this error:
Traceback (most recent call last):
  File "afy/cam_fomm.py", line 316, in <module>
    out = predictor.predict(frame)
  File "C:\Users\JahBlessXen\avatarify-python-youtube\afy\predictor_local.py", line 104, in predict
    use_relative_jacobian=self.relative, adapt_movement_scale=self.adapt_movement_scale)
  File "C:\Users\JahBlessXen\avatarify-python-youtube\afy\predictor_local.py", line 28, in normalize_kp
    jacobian_diff = torch.matmul(kp_driving['jacobian'], torch.inverse(kp_driving_initial['jacobian']))
RuntimeError: CUDA error: operation not supported when calling `cusparseCreate(handle)`

My system specification is as follows:
![Screenshot (1)](https://github.com/alievk/avatarify-python/assets/156550150/0b9509fa-fd44-4d73-9202-dcf93f2a0567)
![Screenshot (2)](https://github.com/alievk/avatarify-python/assets/156550150/6a4ee84e-4b50-46d3-88e4-6b6380916cf8)
![Screenshot (3)](https://github.com/alievk/avatarify-python/assets/156550150/7e4e6c8a-397c-4ba7-8ca2-b1f7c3a35bd3)

**Comment by SanPatrick01** [comment]
Send 
Anydesk to WhatsApp 

‪+2348115133627‬

**Comment by Updatedme** [comment]
For any problem with avatarify , ask me for help on  whatsapp +2347081306010  . 

https://youtube.com/shorts/keEIZVnbT48?si=akCdghB55-zrLddg

**Comment by Updatedme** [comment]
> keep getting this error:
> Traceback (most recent call last):
>   File "afy/cam_fomm.py", line 316, in <module>
>     out = predictor.predict(frame)
>   File "C:\Users\JahBlessXen\avatarify-python-youtube\afy\predictor_local.py", line 104, in predict
>     use_relative_jacobian=self.relative, adapt_movement_scale=self.adapt_movement_scale)
>   File "C:\Users\JahBlessXen\avatarify-python-youtube\afy\predictor_local.py", line 28, in normalize_kp
>     jacobian_diff = torch.matmul(kp_driving['jacobian'], torch.inverse(kp_driving_initial['jacobian']))
> RuntimeError: CUDA error: operation not supported when calling `cusparseCreate(handle)`
> 
> My system specification is as follows:
> ![Screenshot (1)](https://github.com/alievk/avatarify-python/assets/156550150/0b9509fa-fd44-4d73-9202-dcf93f2a0567)
> ![Screenshot (2)](https://github.com/alievk/avatarify-python/assets/156550150/6a4ee84e-4b50-46d3-88e4-6b6380916cf8)
> ![Screenshot (3)](https://github.com/alievk/avatarify-python/assets/156550150/7e4e6c8a-397c-4ba7-8ca2-b1f7c3a35bd3)
> 

For any problem with avatarify , ask me for help on  whatsapp +2347081306010  . 

https://youtube.com/shorts/keEIZVnbT48?si=akCdghB55-zrLddg

**Comment by Updatedme** [comment]
For any problem with avatarify , ask me for help on  whatsapp +2347081306010  . 

https://youtube.com/shorts/keEIZVnbT48?si=akCdghB55-zrLddg

**Comment by Updatedme** [comment]
For any problem with avatarify , ask me for help on  whatsapp +2347081306010  . 

https://youtube.com/shorts/keEIZVnbT48?si=akCdghB55-zrLddg

**Comment by Updatedme** [comment]
For any problem with avatarify , ask me for help on  whatsapp +2347081306010  . 

https://youtube.com/shorts/keEIZVnbT48?si=akCdghB55-zrLddg

**Comment by giantbaobab** [comment]
Hello Guys, I totally get ya, but one of the main reason why Github is in existence is for people to collaborate and help solve technological issues relating to code. It meant to be a safe haven and a place where noobs come to learn through their mistakes and that of others. So please if there is anyway to help out kindly all of us know through the platform, in so doing we will all be learning from each other. Thanks

**Comment by SanPatrick01** [comment]
🥹🥹🥹🥹

**Comment by Updatedme** [comment]
😊 😊

**Comment by peterujah** [comment]
@giantbaobab please did you manage to fix this issue?

**Comment by giantbaobab** [comment]
@peterujah I haven’t resolved it yet.

**Comment by Updatedme** [comment]
> @giantbaobab please did you manage to fix this issue?

Hello , contact me and let me help out , you may not get much of a response here . 
Whatsapp messages +2349064294913

**Comment by Aghogho123** [comment]
![image](https://github.com/alievk/avatarify-python/assets/169853249/02efa93a-4da4-47bc-a62c-7240c022f692)


Am having issues here

**Comment by SanPatrick01** [comment]
What type of laptop

**Comment by Updatedme** [comment]
> ![image](https://github.com/alievk/avatarify-python/assets/169853249/02efa93a-4da4-47bc-a62c-7240c022f692)
> 
> 
> Am having issues here 

For any problem with avatarify , ask me for help on whatsapp +2347081306010 .

**Comment by JohanAR** [comment]
@Aghogho123 check the repository url.. you've both missed two words and spelled the remaining word wrong.

**Comment by eodirah** [comment]
Message me on WhatsApp to help you resolve your avatarify issue and make your avatars have a sharp response
WhatsApp +2348103389491
