### ISSUE TITLE
AttributeError: _2D error and no face detection after change to TWO_D

### ISSUE THREAD

**Issue by peterujah** [alievk/avatarify-python#697]
**Describe the bug**
Please i need help in setting up avatarify on my pc, when i run `run_windows.bat`, it showed below error.

```[1705329854.131797] Loading Predictor
Traceback (most recent call last):
  File "afy/cam_fomm.py", line 218, in <module>
    **predictor_args
  File "C:\Users\User\avatarify-python\afy\predictor_local.py", line 49, in __init__
    self.fa = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D, flip_input=True, device=self.device)
  File "C:\Users\User\miniconda3\envs\avatarify\lib\enum.py", line 354, in __getattr__
    raise AttributeError(name) from None
AttributeError: _2D
```

**To Reproduce**

And i changed line 49 in `predictor_local.py`
from `self.fa = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D, flip_input=True, device=self.device)`
to ` self.fa = face_alignment.FaceAlignment(face_alignment.LandmarksType.TWO_D, flip_input=True, device=self.device)`

And run again, it passed but it shows below warning before opening camera window. but it doesn't detect my face nor preview the window is totally blank.

```C:\Users\User\miniconda3\envs\avatarify\lib\site-packages\torch\nn\functional.py:3103: UserWarning: The default behavior for interpolate/upsample with float scale_factor changed in 1.6.0 to align with other frameworks/libraries, and now uses scale_factor directly, instead of relying on the computed output size. If you wish to restore the old behavior, please set recompute_scale_factor=True. See the documentation of nn.Upsample for details.
  warnings.warn("The default behavior for interpolate/upsample with float scale_factor changed "
```

And when i press `X` on the blank cam window, it exit with below error 
```C:\Users\User\miniconda3\envs\avatarify\lib\site-packages\face_alignment\api.py:147: UserWarning: No faces were detected.
  warnings.warn("No faces were detected.")
Traceback (most recent call last):
  File "afy/cam_fomm.py", line 316, in <module>
    out = predictor.predict(frame)
  File "C:\Users\User\avatarify-python\afy\predictor_local.py", line 104, in predict
    use_relative_jacobian=self.relative, adapt_movement_scale=self.adapt_movement_scale)
  File "C:\Users\User\avatarify-python\afy\predictor_local.py", line 28, in normalize_kp
    jacobian_diff = torch.matmul(kp_driving['jacobian'], torch.inverse(kp_driving_initial['jacobian']))
RuntimeError: CUDA error: operation not supported when calling `cusparseCreate(handle)
````

**What steps can we follow to reproduce the issue?**

**Info (please complete the following information):**
 - OS (e.g., Windows 10 pro): 
 - GPU model: NVIDIA GeForce RTX 4060 Ti

 **Any other relevant information**

[conda_infos.txt](https://github.com/alievk/avatarify-python/files/13940455/conda_infos.txt)
[run_window_bat.txt](https://github.com/alievk/avatarify-python/files/13940456/run_window_bat.txt)

**Screenshots**
![blank_window](https://github.com/alievk/avatarify-python/assets/16369609/4b31f844-622e-45da-a87b-2b21b6286869)

**?**
Yes i have camera, when i run my system camera app, my cam works fine.

**Comment by Updatedme** [comment]
Go to an avatarify folder in the user
Delete the cam.yaml file .
Then, relaunch the program 
 Run_windows.bat 

I want to believe that you are doing this with a gaming pc . 

If that does not work, then ask me for help on whatsapp +2347081306010 .

https://youtube.com/shorts/keEIZVnbT48?si=akCdghB55-zrLddg

**Comment by Urchman7102** [comment]
If you need any help on avatarify related issues contact me on Whatsapp+2349036407102

**Comment by Updatedme** [comment]
If you have any problem with avatarify . Contact me for solutions 100% results on apple macbook and any windows.
You can also watch my installation video that shows you how to do it yourself. Or simply ask for help from my whatsapp contact
https://wa.me/message/GXQYWX4XRTXGB1
+2347081306010

**Comment by seegunz** [comment]
pip install face-alignment==1.0.0 msgpack_numpy pyyaml==6.0.1

**Comment by Nene020** [comment]
Telegram 
@King_Gabos

**Comment by 12ayfa** [comment]
> **Describe the bug** Please i need help in setting up avatarify on my pc, when i run `run_windows.bat`, it showed below error.
> 
> ```
> Traceback (most recent call last):
>   File "afy/cam_fomm.py", line 218, in <module>
>     **predictor_args
>   File "C:\Users\User\avatarify-python\afy\predictor_local.py", line 49, in __init__
>     self.fa = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D, flip_input=True, device=self.device)
>   File "C:\Users\User\miniconda3\envs\avatarify\lib\enum.py", line 354, in __getattr__
>     raise AttributeError(name) from None
> AttributeError: _2D
> ```
> 
> **To Reproduce**
> 
> And i changed line 49 in `predictor_local.py` from `self.fa = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D, flip_input=True, device=self.device)` to ` self.fa = face_alignment.FaceAlignment(face_alignment.LandmarksType.TWO_D, flip_input=True, device=self.device)`
> 
> And run again, it passed but it shows below warning before opening camera window. but it doesn't detect my face nor preview the window is totally blank.
> 
> `C:\Users\User\miniconda3\envs\avatarify\lib\site-packages\torch\nn\functional.py:3103: UserWarning: The default behavior for interpolate/upsample with float scale_factor changed in 1.6.0 to align with other frameworks/libraries, and now uses scale_factor directly, instead of relying on the computed output size. If you wish to restore the old behavior, please set recompute_scale_factor=True. See the documentation of nn.Upsample for details. warnings.warn("The default behavior for interpolate/upsample with float scale_factor changed")`
> 
> And when i press `X` on the blank cam window, it exit with below error
> 
> ```
>   warnings.warn("No faces were detected.")
> Traceback (most recent call last):
>   File "afy/cam_fomm.py", line 316, in <module>
>     out = predictor.predict(frame)
>   File "C:\Users\User\avatarify-python\afy\predictor_local.py", line 104, in predict
>     use_relative_jacobian=self.relative, adapt_movement_scale=self.adapt_movement_scale)
>   File "C:\Users\User\avatarify-python\afy\predictor_local.py", line 28, in normalize_kp
>     jacobian_diff = torch.matmul(kp_driving['jacobian'], torch.inverse(kp_driving_initial['jacobian']))
> RuntimeError: CUDA error: operation not supported when calling `cusparseCreate(handle)
> ```
> 
> **What steps can we follow to reproduce the issue?**
> 
> **Info (please complete the following information):**
> 
> * OS (e.g., Windows 10 pro):
> * GPU model: NVIDIA GeForce RTX 4060 Ti
> 
> **Any other relevant information**
> 
> [conda_infos.txt](https://github.com/alievk/avatarify-python/files/13940455/conda_infos.txt) [run_window_bat.txt](https://github.com/alievk/avatarify-python/files/13940456/run_window_bat.txt)
> 
> **Screenshots** ![blank_window](https://private-user-images.githubusercontent.com/16369609/296798289-4b31f844-622e-45da-a87b-2b21b6286869.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwMjMwODIsIm5iZiI6MTcyOTAyMjc4MiwicGF0aCI6Ii8xNjM2OTYwOS8yOTY3OTgyODktNGIzMWY4NDQtNjIyZS00NWRhLWE4N2ItMmIyMWI2Mjg2ODY5LlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDIwMDYyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxODFjM2IzYTJjNjVlOWQ5OTg0MDc0OGFhZjhhNjk1MjZhNGNhYmU3MTc1OWUwYmMzY2JlNGVjNDA0MGMwOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.L7bbusxX3wGD9-6MtWXc9g3hNM-3573eFRvvGx1PP1o)
> 
> **?** Yes i have camera, when i run my system camera app, my cam works fine.

Did you get it resolved? 
Please help how to change 2D to TWO D
